# encoding: utf-8
require File.expand_path(File.dirname(__FILE__)) + '/../test_helper'

# This file is generated by the Ruby Holiday gem.
#
# Definitions loaded: definitions/ca.yaml, definitions/north_america_informal.yaml
class CaDefinitionTests < Test::Unit::TestCase  # :nodoc:

  def test_ca
    holidays = Holidays.on(Date.civil(2008, 1, 1), [:ca], [:informal])
    matching_holiday = holidays.find { |hol| hol[:name] == "New Year's Day" }
    assert_not_nil matching_holiday
    assert_equal Date.civil(2008, 1, 1), matching_holiday[:date]
    assert_includes matching_holiday[:regions], :ca


    holidays = Holidays.on(Date.civil(2008, 3, 21), [:ca], [:informal])
    matching_holiday = holidays.find { |hol| hol[:name] == "Good Friday" }
    assert_not_nil matching_holiday
    assert_equal Date.civil(2008, 3, 21), matching_holiday[:date]
    assert_includes matching_holiday[:regions], :ca


    holidays = Holidays.on(Date.civil(2013, 3, 31), [:ca], [:informal])
    matching_holiday = holidays.find { |hol| hol[:name] == "Easter Sunday" }
    assert_not_nil matching_holiday
    assert_equal Date.civil(2013, 3, 31), matching_holiday[:date]
    assert_includes matching_holiday[:regions], :ca


    holidays = Holidays.on(Date.civil(2008, 3, 24), [:ca], [:informal])
    matching_holiday = holidays.find { |hol| hol[:name] == "Easter Monday" }
    assert_not_nil matching_holiday
    assert_equal Date.civil(2008, 3, 24), matching_holiday[:date]
    assert_includes matching_holiday[:regions], :ca


    holidays = Holidays.on(Date.civil(2008, 7, 1), [:ca], [:informal])
    matching_holiday = holidays.find { |hol| hol[:name] == "Canada Day" }
    assert_not_nil matching_holiday
    assert_equal Date.civil(2008, 7, 1), matching_holiday[:date]
    assert_includes matching_holiday[:regions], :ca


    holidays = Holidays.on(Date.civil(2008, 9, 1), [:ca], [:informal])
    matching_holiday = holidays.find { |hol| hol[:name] == "Labour Day" }
    assert_not_nil matching_holiday
    assert_equal Date.civil(2008, 9, 1), matching_holiday[:date]
    assert_includes matching_holiday[:regions], :ca


    holidays = Holidays.on(Date.civil(2008, 12, 25), [:ca], [:informal])
    matching_holiday = holidays.find { |hol| hol[:name] == "Christmas Day" }
    assert_not_nil matching_holiday
    assert_equal Date.civil(2008, 12, 25), matching_holiday[:date]
    assert_includes matching_holiday[:regions], :ca


    holidays = Holidays.on(Date.civil(1990, 2, 19), [:ca_ab])
    matching_holiday = holidays.find { |hol| hol[:name] == "Family Day" }
    assert_not_nil matching_holiday
    assert_equal Date.civil(1990, 2, 19), matching_holiday[:date]
    assert_includes matching_holiday[:regions], :ca_ab


    holidays = Holidays.on(Date.civil(2013, 2, 18), [:ca_ab])
    matching_holiday = holidays.find { |hol| hol[:name] == "Family Day" }
    assert_not_nil matching_holiday
    assert_equal Date.civil(2013, 2, 18), matching_holiday[:date]
    assert_includes matching_holiday[:regions], :ca_ab


    holidays = Holidays.on(Date.civil(2014, 2, 17), [:ca_ab])
    matching_holiday = holidays.find { |hol| hol[:name] == "Family Day" }
    assert_not_nil matching_holiday
    assert_equal Date.civil(2014, 2, 17), matching_holiday[:date]
    assert_includes matching_holiday[:regions], :ca_ab


    holidays = Holidays.on(Date.civil(2044, 2, 15), [:ca_ab])
    matching_holiday = holidays.find { |hol| hol[:name] == "Family Day" }
    assert_not_nil matching_holiday
    assert_equal Date.civil(2044, 2, 15), matching_holiday[:date]
    assert_includes matching_holiday[:regions], :ca_ab


    assert_nil (Holidays.on(Date.civil(1970, 2, 16), [:ca_ab])[0] || {})[:name]

    assert_nil (Holidays.on(Date.civil(1988, 2, 15), [:ca_ab])[0] || {})[:name]

    assert_nil (Holidays.on(Date.civil(1989, 2, 20), [:ca_ab])[0] || {})[:name]

    holidays = Holidays.on(Date.civil(2007, 2, 19), [:ca_sk])
    matching_holiday = holidays.find { |hol| hol[:name] == "Family Day" }
    assert_not_nil matching_holiday
    assert_equal Date.civil(2007, 2, 19), matching_holiday[:date]
    assert_includes matching_holiday[:regions], :ca_sk


    holidays = Holidays.on(Date.civil(2013, 2, 18), [:ca_sk])
    matching_holiday = holidays.find { |hol| hol[:name] == "Family Day" }
    assert_not_nil matching_holiday
    assert_equal Date.civil(2013, 2, 18), matching_holiday[:date]
    assert_includes matching_holiday[:regions], :ca_sk


    holidays = Holidays.on(Date.civil(2014, 2, 17), [:ca_sk])
    matching_holiday = holidays.find { |hol| hol[:name] == "Family Day" }
    assert_not_nil matching_holiday
    assert_equal Date.civil(2014, 2, 17), matching_holiday[:date]
    assert_includes matching_holiday[:regions], :ca_sk


    holidays = Holidays.on(Date.civil(2044, 2, 15), [:ca_sk])
    matching_holiday = holidays.find { |hol| hol[:name] == "Family Day" }
    assert_not_nil matching_holiday
    assert_equal Date.civil(2044, 2, 15), matching_holiday[:date]
    assert_includes matching_holiday[:regions], :ca_sk


    assert_nil (Holidays.on(Date.civil(1970, 2, 16), [:ca_sk])[0] || {})[:name]

    assert_nil (Holidays.on(Date.civil(1988, 2, 15), [:ca_sk])[0] || {})[:name]

    assert_nil (Holidays.on(Date.civil(1989, 2, 20), [:ca_sk])[0] || {})[:name]

    assert_nil (Holidays.on(Date.civil(2006, 2, 20), [:ca_sk])[0] || {})[:name]

    holidays = Holidays.on(Date.civil(2008, 2, 18), [:ca_on])
    matching_holiday = holidays.find { |hol| hol[:name] == "Family Day" }
    assert_not_nil matching_holiday
    assert_equal Date.civil(2008, 2, 18), matching_holiday[:date]
    assert_includes matching_holiday[:regions], :ca_on


    holidays = Holidays.on(Date.civil(2013, 2, 18), [:ca_on])
    matching_holiday = holidays.find { |hol| hol[:name] == "Family Day" }
    assert_not_nil matching_holiday
    assert_equal Date.civil(2013, 2, 18), matching_holiday[:date]
    assert_includes matching_holiday[:regions], :ca_on


    holidays = Holidays.on(Date.civil(2014, 2, 17), [:ca_on])
    matching_holiday = holidays.find { |hol| hol[:name] == "Family Day" }
    assert_not_nil matching_holiday
    assert_equal Date.civil(2014, 2, 17), matching_holiday[:date]
    assert_includes matching_holiday[:regions], :ca_on


    holidays = Holidays.on(Date.civil(2044, 2, 15), [:ca_on])
    matching_holiday = holidays.find { |hol| hol[:name] == "Family Day" }
    assert_not_nil matching_holiday
    assert_equal Date.civil(2044, 2, 15), matching_holiday[:date]
    assert_includes matching_holiday[:regions], :ca_on


    assert_nil (Holidays.on(Date.civil(1970, 2, 16), [:ca_on])[0] || {})[:name]

    assert_nil (Holidays.on(Date.civil(1988, 2, 15), [:ca_on])[0] || {})[:name]

    assert_nil (Holidays.on(Date.civil(1989, 2, 20), [:ca_on])[0] || {})[:name]

    assert_nil (Holidays.on(Date.civil(2006, 2, 20), [:ca_on])[0] || {})[:name]

    assert_nil (Holidays.on(Date.civil(2007, 2, 19), [:ca_on])[0] || {})[:name]

    holidays = Holidays.on(Date.civil(2013, 2, 11), [:ca_bc])
    matching_holiday = holidays.find { |hol| hol[:name] == "Family Day" }
    assert_not_nil matching_holiday
    assert_equal Date.civil(2013, 2, 11), matching_holiday[:date]
    assert_includes matching_holiday[:regions], :ca_bc


    holidays = Holidays.on(Date.civil(2014, 2, 10), [:ca_bc])
    matching_holiday = holidays.find { |hol| hol[:name] == "Family Day" }
    assert_not_nil matching_holiday
    assert_equal Date.civil(2014, 2, 10), matching_holiday[:date]
    assert_includes matching_holiday[:regions], :ca_bc


    holidays = Holidays.on(Date.civil(2044, 2, 8), [:ca_bc])
    matching_holiday = holidays.find { |hol| hol[:name] == "Family Day" }
    assert_not_nil matching_holiday
    assert_equal Date.civil(2044, 2, 8), matching_holiday[:date]
    assert_includes matching_holiday[:regions], :ca_bc


    assert_nil (Holidays.on(Date.civil(2000, 2, 14), [:ca_bc])[0] || {})[:name]

    assert_nil (Holidays.on(Date.civil(2011, 2, 14), [:ca_bc])[0] || {})[:name]

    assert_nil (Holidays.on(Date.civil(2012, 2, 13), [:ca_bc])[0] || {})[:name]

    holidays = Holidays.on(Date.civil(2018, 2, 19), [:ca_nb])
    matching_holiday = holidays.find { |hol| hol[:name] == "Family Day" }
    assert_not_nil matching_holiday
    assert_equal Date.civil(2018, 2, 19), matching_holiday[:date]
    assert_includes matching_holiday[:regions], :ca_nb


    holidays = Holidays.on(Date.civil(2019, 2, 18), [:ca_nb])
    matching_holiday = holidays.find { |hol| hol[:name] == "Family Day" }
    assert_not_nil matching_holiday
    assert_equal Date.civil(2019, 2, 18), matching_holiday[:date]
    assert_includes matching_holiday[:regions], :ca_nb


    assert_nil (Holidays.on(Date.civil(2016, 2, 18), [:ca_nb])[0] || {})[:name]

    assert_nil (Holidays.on(Date.civil(2017, 2, 20), [:ca_nb])[0] || {})[:name]

    holidays = Holidays.on(Date.civil(2015, 2, 16), [:ca_ns])
    matching_holiday = holidays.find { |hol| hol[:name] == "Nova Scotia Heritage Day" }
    assert_not_nil matching_holiday
    assert_equal Date.civil(2015, 2, 16), matching_holiday[:date]
    assert_includes matching_holiday[:regions], :ca_ns


    holidays = Holidays.on(Date.civil(2016, 2, 15), [:ca_ns])
    matching_holiday = holidays.find { |hol| hol[:name] == "Nova Scotia Heritage Day" }
    assert_not_nil matching_holiday
    assert_equal Date.civil(2016, 2, 15), matching_holiday[:date]
    assert_includes matching_holiday[:regions], :ca_ns


    holidays = Holidays.on(Date.civil(2017, 2, 20), [:ca_ns])
    matching_holiday = holidays.find { |hol| hol[:name] == "Nova Scotia Heritage Day" }
    assert_not_nil matching_holiday
    assert_equal Date.civil(2017, 2, 20), matching_holiday[:date]
    assert_includes matching_holiday[:regions], :ca_ns


    holidays = Holidays.on(Date.civil(2044, 2, 15), [:ca_ns])
    matching_holiday = holidays.find { |hol| hol[:name] == "Nova Scotia Heritage Day" }
    assert_not_nil matching_holiday
    assert_equal Date.civil(2044, 2, 15), matching_holiday[:date]
    assert_includes matching_holiday[:regions], :ca_ns


    assert_nil (Holidays.on(Date.civil(2000, 2, 21), [:ca_ns])[0] || {})[:name]

    assert_nil (Holidays.on(Date.civil(2012, 2, 20), [:ca_ns])[0] || {})[:name]

    assert_nil (Holidays.on(Date.civil(2013, 2, 18), [:ca_ns])[0] || {})[:name]

    assert_nil (Holidays.on(Date.civil(2014, 2, 17), [:ca_ns])[0] || {})[:name]

    holidays = Holidays.on(Date.civil(2013, 2, 18), [:ca_pe])
    matching_holiday = holidays.find { |hol| hol[:name] == "Islander Day" }
    assert_not_nil matching_holiday
    assert_equal Date.civil(2013, 2, 18), matching_holiday[:date]
    assert_includes matching_holiday[:regions], :ca_pe


    holidays = Holidays.on(Date.civil(2014, 2, 17), [:ca_pe])
    matching_holiday = holidays.find { |hol| hol[:name] == "Islander Day" }
    assert_not_nil matching_holiday
    assert_equal Date.civil(2014, 2, 17), matching_holiday[:date]
    assert_includes matching_holiday[:regions], :ca_pe


    holidays = Holidays.on(Date.civil(2004, 5, 24), [:ca_ab, :ca_bc, :ca_mb, :ca_nt, :ca_nu, :ca_on, :ca_sk, :ca_yt])
    matching_holiday = holidays.find { |hol| hol[:name] == "Victoria Day" }
    assert_not_nil matching_holiday
    assert_equal Date.civil(2004, 5, 24), matching_holiday[:date]
    assert_includes matching_holiday[:regions], :ca_ab
    assert_includes matching_holiday[:regions], :ca_bc
    assert_includes matching_holiday[:regions], :ca_mb
    assert_includes matching_holiday[:regions], :ca_nt
    assert_includes matching_holiday[:regions], :ca_nu
    assert_includes matching_holiday[:regions], :ca_on
    assert_includes matching_holiday[:regions], :ca_sk
    assert_includes matching_holiday[:regions], :ca_yt

    holidays = Holidays.on(Date.civil(2005, 5, 23), [:ca_ab, :ca_bc, :ca_mb, :ca_nt, :ca_nu, :ca_on, :ca_sk, :ca_yt])
    matching_holiday = holidays.find { |hol| hol[:name] == "Victoria Day" }
    assert_not_nil matching_holiday
    assert_equal Date.civil(2005, 5, 23), matching_holiday[:date]
    assert_includes matching_holiday[:regions], :ca_ab
    assert_includes matching_holiday[:regions], :ca_bc
    assert_includes matching_holiday[:regions], :ca_mb
    assert_includes matching_holiday[:regions], :ca_nt
    assert_includes matching_holiday[:regions], :ca_nu
    assert_includes matching_holiday[:regions], :ca_on
    assert_includes matching_holiday[:regions], :ca_sk
    assert_includes matching_holiday[:regions], :ca_yt

    holidays = Holidays.on(Date.civil(2006, 5, 22), [:ca_ab, :ca_bc, :ca_mb, :ca_nt, :ca_nu, :ca_on, :ca_sk, :ca_yt])
    matching_holiday = holidays.find { |hol| hol[:name] == "Victoria Day" }
    assert_not_nil matching_holiday
    assert_equal Date.civil(2006, 5, 22), matching_holiday[:date]
    assert_includes matching_holiday[:regions], :ca_ab
    assert_includes matching_holiday[:regions], :ca_bc
    assert_includes matching_holiday[:regions], :ca_mb
    assert_includes matching_holiday[:regions], :ca_nt
    assert_includes matching_holiday[:regions], :ca_nu
    assert_includes matching_holiday[:regions], :ca_on
    assert_includes matching_holiday[:regions], :ca_sk
    assert_includes matching_holiday[:regions], :ca_yt

    holidays = Holidays.on(Date.civil(2007, 5, 21), [:ca_ab, :ca_bc, :ca_mb, :ca_nt, :ca_nu, :ca_on, :ca_sk, :ca_yt])
    matching_holiday = holidays.find { |hol| hol[:name] == "Victoria Day" }
    assert_not_nil matching_holiday
    assert_equal Date.civil(2007, 5, 21), matching_holiday[:date]
    assert_includes matching_holiday[:regions], :ca_ab
    assert_includes matching_holiday[:regions], :ca_bc
    assert_includes matching_holiday[:regions], :ca_mb
    assert_includes matching_holiday[:regions], :ca_nt
    assert_includes matching_holiday[:regions], :ca_nu
    assert_includes matching_holiday[:regions], :ca_on
    assert_includes matching_holiday[:regions], :ca_sk
    assert_includes matching_holiday[:regions], :ca_yt

    holidays = Holidays.on(Date.civil(2008, 5, 19), [:ca_ab, :ca_bc, :ca_mb, :ca_nt, :ca_nu, :ca_on, :ca_sk, :ca_yt])
    matching_holiday = holidays.find { |hol| hol[:name] == "Victoria Day" }
    assert_not_nil matching_holiday
    assert_equal Date.civil(2008, 5, 19), matching_holiday[:date]
    assert_includes matching_holiday[:regions], :ca_ab
    assert_includes matching_holiday[:regions], :ca_bc
    assert_includes matching_holiday[:regions], :ca_mb
    assert_includes matching_holiday[:regions], :ca_nt
    assert_includes matching_holiday[:regions], :ca_nu
    assert_includes matching_holiday[:regions], :ca_on
    assert_includes matching_holiday[:regions], :ca_sk
    assert_includes matching_holiday[:regions], :ca_yt


    holidays = Holidays.on(Date.civil(2013, 8, 5), [:ca_bc])
    matching_holiday = holidays.find { |hol| hol[:name] == "B.C. Day" }
    assert_not_nil matching_holiday
    assert_equal Date.civil(2013, 8, 5), matching_holiday[:date]
    assert_includes matching_holiday[:regions], :ca_bc


    holidays = Holidays.on(Date.civil(2013, 8, 5), [:ca_sk])
    matching_holiday = holidays.find { |hol| hol[:name] == "Saskatchewan Day" }
    assert_not_nil matching_holiday
    assert_equal Date.civil(2013, 8, 5), matching_holiday[:date]
    assert_includes matching_holiday[:regions], :ca_sk


    holidays = Holidays.on(Date.civil(2013, 8, 5), [:ca_ab], [:informal])
    matching_holiday = holidays.find { |hol| hol[:name] == "Heritage Day" }
    assert_not_nil matching_holiday
    assert_equal Date.civil(2013, 8, 5), matching_holiday[:date]
    assert_includes matching_holiday[:regions], :ca_ab


    holidays = Holidays.on(Date.civil(2013, 8, 5), [:ca_ns], [:informal])
    matching_holiday = holidays.find { |hol| hol[:name] == "Natal Day" }
    assert_not_nil matching_holiday
    assert_equal Date.civil(2013, 8, 5), matching_holiday[:date]
    assert_includes matching_holiday[:regions], :ca_ns


    holidays = Holidays.on(Date.civil(2013, 8, 5), [:ca_on], [:informal])
    matching_holiday = holidays.find { |hol| hol[:name] == "Civic Holiday" }
    assert_not_nil matching_holiday
    assert_equal Date.civil(2013, 8, 5), matching_holiday[:date]
    assert_includes matching_holiday[:regions], :ca_on

    holidays = Holidays.on(Date.civil(2014, 8, 4), [:ca_on], [:informal])
    matching_holiday = holidays.find { |hol| hol[:name] == "Civic Holiday" }
    assert_not_nil matching_holiday
    assert_equal Date.civil(2014, 8, 4), matching_holiday[:date]
    assert_includes matching_holiday[:regions], :ca_on

    holidays = Holidays.on(Date.civil(2015, 8, 3), [:ca_on], [:informal])
    matching_holiday = holidays.find { |hol| hol[:name] == "Civic Holiday" }
    assert_not_nil matching_holiday
    assert_equal Date.civil(2015, 8, 3), matching_holiday[:date]
    assert_includes matching_holiday[:regions], :ca_on


    holidays = Holidays.on(Date.civil(2013, 8, 5), [:ca_nt])
    matching_holiday = holidays.find { |hol| hol[:name] == "Civic Holiday" }
    assert_not_nil matching_holiday
    assert_equal Date.civil(2013, 8, 5), matching_holiday[:date]
    assert_includes matching_holiday[:regions], :ca_nt


    holidays = Holidays.on(Date.civil(2013, 8, 5), [:ca_nu])
    matching_holiday = holidays.find { |hol| hol[:name] == "Civic Holiday" }
    assert_not_nil matching_holiday
    assert_equal Date.civil(2013, 8, 5), matching_holiday[:date]
    assert_includes matching_holiday[:regions], :ca_nu


    holidays = Holidays.on(Date.civil(2013, 8, 5), [:ca_pe], [:informal])
    matching_holiday = holidays.find { |hol| hol[:name] == "Civic Holiday" }
    assert_not_nil matching_holiday
    assert_equal Date.civil(2013, 8, 5), matching_holiday[:date]
    assert_includes matching_holiday[:regions], :ca_pe


    holidays = Holidays.on(Date.civil(2013, 8, 5), [:ca_nb])
    matching_holiday = holidays.find { |hol| hol[:name] == "New Brunswick Day" }
    assert_not_nil matching_holiday
    assert_equal Date.civil(2013, 8, 5), matching_holiday[:date]
    assert_includes matching_holiday[:regions], :ca_nb


    holidays = Holidays.on(Date.civil(2014, 8, 4), [:ca_bc])
    matching_holiday = holidays.find { |hol| hol[:name] == "B.C. Day" }
    assert_not_nil matching_holiday
    assert_equal Date.civil(2014, 8, 4), matching_holiday[:date]
    assert_includes matching_holiday[:regions], :ca_bc


    holidays = Holidays.on(Date.civil(2014, 8, 4), [:ca_sk])
    matching_holiday = holidays.find { |hol| hol[:name] == "Saskatchewan Day" }
    assert_not_nil matching_holiday
    assert_equal Date.civil(2014, 8, 4), matching_holiday[:date]
    assert_includes matching_holiday[:regions], :ca_sk


    holidays = Holidays.on(Date.civil(2014, 8, 4), [:ca_ab], [:informal])
    matching_holiday = holidays.find { |hol| hol[:name] == "Heritage Day" }
    assert_not_nil matching_holiday
    assert_equal Date.civil(2014, 8, 4), matching_holiday[:date]
    assert_includes matching_holiday[:regions], :ca_ab


    holidays = Holidays.on(Date.civil(2014, 8, 4), [:ca_ns], [:informal])
    matching_holiday = holidays.find { |hol| hol[:name] == "Natal Day" }
    assert_not_nil matching_holiday
    assert_equal Date.civil(2014, 8, 4), matching_holiday[:date]
    assert_includes matching_holiday[:regions], :ca_ns


    holidays = Holidays.on(Date.civil(2014, 8, 4), [:ca_nt])
    matching_holiday = holidays.find { |hol| hol[:name] == "Civic Holiday" }
    assert_not_nil matching_holiday
    assert_equal Date.civil(2014, 8, 4), matching_holiday[:date]
    assert_includes matching_holiday[:regions], :ca_nt


    holidays = Holidays.on(Date.civil(2014, 8, 4), [:ca_nu])
    matching_holiday = holidays.find { |hol| hol[:name] == "Civic Holiday" }
    assert_not_nil matching_holiday
    assert_equal Date.civil(2014, 8, 4), matching_holiday[:date]
    assert_includes matching_holiday[:regions], :ca_nu


    holidays = Holidays.on(Date.civil(2014, 8, 4), [:ca_pe], [:informal])
    matching_holiday = holidays.find { |hol| hol[:name] == "Civic Holiday" }
    assert_not_nil matching_holiday
    assert_equal Date.civil(2014, 8, 4), matching_holiday[:date]
    assert_includes matching_holiday[:regions], :ca_pe


    holidays = Holidays.on(Date.civil(2014, 8, 4), [:ca_nb])
    matching_holiday = holidays.find { |hol| hol[:name] == "New Brunswick Day" }
    assert_not_nil matching_holiday
    assert_equal Date.civil(2014, 8, 4), matching_holiday[:date]
    assert_includes matching_holiday[:regions], :ca_nb


    holidays = Holidays.on(Date.civil(2015, 8, 3), [:ca_bc])
    matching_holiday = holidays.find { |hol| hol[:name] == "B.C. Day" }
    assert_not_nil matching_holiday
    assert_equal Date.civil(2015, 8, 3), matching_holiday[:date]
    assert_includes matching_holiday[:regions], :ca_bc


    holidays = Holidays.on(Date.civil(2015, 8, 3), [:ca_sk])
    matching_holiday = holidays.find { |hol| hol[:name] == "Saskatchewan Day" }
    assert_not_nil matching_holiday
    assert_equal Date.civil(2015, 8, 3), matching_holiday[:date]
    assert_includes matching_holiday[:regions], :ca_sk


    holidays = Holidays.on(Date.civil(2015, 8, 3), [:ca_ab], [:informal])
    matching_holiday = holidays.find { |hol| hol[:name] == "Heritage Day" }
    assert_not_nil matching_holiday
    assert_equal Date.civil(2015, 8, 3), matching_holiday[:date]
    assert_includes matching_holiday[:regions], :ca_ab


    holidays = Holidays.on(Date.civil(2015, 8, 3), [:ca_ns], [:informal])
    matching_holiday = holidays.find { |hol| hol[:name] == "Natal Day" }
    assert_not_nil matching_holiday
    assert_equal Date.civil(2015, 8, 3), matching_holiday[:date]
    assert_includes matching_holiday[:regions], :ca_ns


    holidays = Holidays.on(Date.civil(2015, 8, 3), [:ca_nt])
    matching_holiday = holidays.find { |hol| hol[:name] == "Civic Holiday" }
    assert_not_nil matching_holiday
    assert_equal Date.civil(2015, 8, 3), matching_holiday[:date]
    assert_includes matching_holiday[:regions], :ca_nt


    holidays = Holidays.on(Date.civil(2015, 8, 3), [:ca_nu])
    matching_holiday = holidays.find { |hol| hol[:name] == "Civic Holiday" }
    assert_not_nil matching_holiday
    assert_equal Date.civil(2015, 8, 3), matching_holiday[:date]
    assert_includes matching_holiday[:regions], :ca_nu


    holidays = Holidays.on(Date.civil(2015, 8, 3), [:ca_pe], [:informal])
    matching_holiday = holidays.find { |hol| hol[:name] == "Civic Holiday" }
    assert_not_nil matching_holiday
    assert_equal Date.civil(2015, 8, 3), matching_holiday[:date]
    assert_includes matching_holiday[:regions], :ca_pe


    holidays = Holidays.on(Date.civil(2015, 8, 3), [:ca_nb])
    matching_holiday = holidays.find { |hol| hol[:name] == "New Brunswick Day" }
    assert_not_nil matching_holiday
    assert_equal Date.civil(2015, 8, 3), matching_holiday[:date]
    assert_includes matching_holiday[:regions], :ca_nb


    holidays = Holidays.on(Date.civil(2010, 11, 11), [:ca_ab, :ca_sk, :ca_bc, :ca_pe, :ca_nl, :ca_nt, :ca_nu, :ca_nb, :ca_yt], [:observed])
    matching_holiday = holidays.find { |hol| hol[:name] == "Remembrance Day" }
    assert_not_nil matching_holiday
    assert_equal Date.civil(2010, 11, 11), matching_holiday[:date]
    assert_includes matching_holiday[:regions], :ca_ab
    assert_includes matching_holiday[:regions], :ca_sk
    assert_includes matching_holiday[:regions], :ca_bc
    assert_includes matching_holiday[:regions], :ca_pe
    assert_includes matching_holiday[:regions], :ca_nl
    assert_includes matching_holiday[:regions], :ca_nt
    assert_includes matching_holiday[:regions], :ca_nu
    assert_includes matching_holiday[:regions], :ca_nb
    assert_includes matching_holiday[:regions], :ca_yt

    holidays = Holidays.on(Date.civil(2012, 11, 12), [:ca_ab, :ca_sk, :ca_bc, :ca_pe, :ca_nl, :ca_nt, :ca_nu, :ca_nb, :ca_yt], [:observed])
    matching_holiday = holidays.find { |hol| hol[:name] == "Remembrance Day" }
    assert_not_nil matching_holiday
    assert_equal Date.civil(2012, 11, 12), matching_holiday[:date]
    assert_includes matching_holiday[:regions], :ca_ab
    assert_includes matching_holiday[:regions], :ca_sk
    assert_includes matching_holiday[:regions], :ca_bc
    assert_includes matching_holiday[:regions], :ca_pe
    assert_includes matching_holiday[:regions], :ca_nl
    assert_includes matching_holiday[:regions], :ca_nt
    assert_includes matching_holiday[:regions], :ca_nu
    assert_includes matching_holiday[:regions], :ca_nb
    assert_includes matching_holiday[:regions], :ca_yt

    holidays = Holidays.on(Date.civil(2017, 11, 13), [:ca_ab, :ca_sk, :ca_bc, :ca_pe, :ca_nl, :ca_nt, :ca_nu, :ca_nb, :ca_yt], [:observed])
    matching_holiday = holidays.find { |hol| hol[:name] == "Remembrance Day" }
    assert_not_nil matching_holiday
    assert_equal Date.civil(2017, 11, 13), matching_holiday[:date]
    assert_includes matching_holiday[:regions], :ca_ab
    assert_includes matching_holiday[:regions], :ca_sk
    assert_includes matching_holiday[:regions], :ca_bc
    assert_includes matching_holiday[:regions], :ca_pe
    assert_includes matching_holiday[:regions], :ca_nl
    assert_includes matching_holiday[:regions], :ca_nt
    assert_includes matching_holiday[:regions], :ca_nu
    assert_includes matching_holiday[:regions], :ca_nb
    assert_includes matching_holiday[:regions], :ca_yt


    holidays = Holidays.on(Date.civil(2016, 11, 11), [:ca_ab, :ca_sk, :ca_bc, :ca_pe, :ca_nl, :ca_nt, :ca_nu, :ca_nb, :ca_yt])
    matching_holiday = holidays.find { |hol| hol[:name] == "Remembrance Day" }
    assert_not_nil matching_holiday
    assert_equal Date.civil(2016, 11, 11), matching_holiday[:date]
    assert_includes matching_holiday[:regions], :ca_ab
    assert_includes matching_holiday[:regions], :ca_sk
    assert_includes matching_holiday[:regions], :ca_bc
    assert_includes matching_holiday[:regions], :ca_pe
    assert_includes matching_holiday[:regions], :ca_nl
    assert_includes matching_holiday[:regions], :ca_nt
    assert_includes matching_holiday[:regions], :ca_nu
    assert_includes matching_holiday[:regions], :ca_nb
    assert_includes matching_holiday[:regions], :ca_yt


    holidays = Holidays.on(Date.civil(2011, 1, 3), [:ca], [:observed])
    matching_holiday = holidays.find { |hol| hol[:name] == "New Year's Day" }
    assert_not_nil matching_holiday
    assert_equal Date.civil(2011, 1, 3), matching_holiday[:date]
    assert_includes matching_holiday[:regions], :ca


    holidays = Holidays.on(Date.civil(2012, 1, 2), [:ca], [:observed])
    matching_holiday = holidays.find { |hol| hol[:name] == "New Year's Day" }
    assert_not_nil matching_holiday
    assert_equal Date.civil(2012, 1, 2), matching_holiday[:date]
    assert_includes matching_holiday[:regions], :ca


    holidays = Holidays.on(Date.civil(2016, 1, 1), [:ca], [:observed])
    matching_holiday = holidays.find { |hol| hol[:name] == "New Year's Day" }
    assert_not_nil matching_holiday
    assert_equal Date.civil(2016, 1, 1), matching_holiday[:date]
    assert_includes matching_holiday[:regions], :ca


    holidays = Holidays.on(Date.civil(2011, 7, 1), [:ca], [:observed])
    matching_holiday = holidays.find { |hol| hol[:name] == "Canada Day" }
    assert_not_nil matching_holiday
    assert_equal Date.civil(2011, 7, 1), matching_holiday[:date]
    assert_includes matching_holiday[:regions], :ca


    holidays = Holidays.on(Date.civil(2012, 7, 2), [:ca], [:observed])
    matching_holiday = holidays.find { |hol| hol[:name] == "Canada Day" }
    assert_not_nil matching_holiday
    assert_equal Date.civil(2012, 7, 2), matching_holiday[:date]
    assert_includes matching_holiday[:regions], :ca


    holidays = Holidays.on(Date.civil(2017, 7, 3), [:ca], [:observed])
    matching_holiday = holidays.find { |hol| hol[:name] == "Canada Day" }
    assert_not_nil matching_holiday
    assert_equal Date.civil(2017, 7, 3), matching_holiday[:date]
    assert_includes matching_holiday[:regions], :ca


    holidays = Holidays.on(Date.civil(2010, 12, 27), [:ca], [:observed])
    matching_holiday = holidays.find { |hol| hol[:name] == "Christmas Day" }
    assert_not_nil matching_holiday
    assert_equal Date.civil(2010, 12, 27), matching_holiday[:date]
    assert_includes matching_holiday[:regions], :ca


    holidays = Holidays.on(Date.civil(2012, 12, 25), [:ca], [:observed])
    matching_holiday = holidays.find { |hol| hol[:name] == "Christmas Day" }
    assert_not_nil matching_holiday
    assert_equal Date.civil(2012, 12, 25), matching_holiday[:date]
    assert_includes matching_holiday[:regions], :ca


    holidays = Holidays.on(Date.civil(2016, 12, 26), [:ca], [:observed])
    matching_holiday = holidays.find { |hol| hol[:name] == "Christmas Day" }
    assert_not_nil matching_holiday
    assert_equal Date.civil(2016, 12, 26), matching_holiday[:date]
    assert_includes matching_holiday[:regions], :ca


    holidays = Holidays.on(Date.civil(2010, 12, 28), [:ca_on], [:observed])
    matching_holiday = holidays.find { |hol| hol[:name] == "Boxing Day" }
    assert_not_nil matching_holiday
    assert_equal Date.civil(2010, 12, 28), matching_holiday[:date]
    assert_includes matching_holiday[:regions], :ca_on

    holidays = Holidays.on(Date.civil(2012, 12, 26), [:ca_on], [:observed])
    matching_holiday = holidays.find { |hol| hol[:name] == "Boxing Day" }
    assert_not_nil matching_holiday
    assert_equal Date.civil(2012, 12, 26), matching_holiday[:date]
    assert_includes matching_holiday[:regions], :ca_on

    holidays = Holidays.on(Date.civil(2015, 12, 28), [:ca_on], [:observed])
    matching_holiday = holidays.find { |hol| hol[:name] == "Boxing Day" }
    assert_not_nil matching_holiday
    assert_equal Date.civil(2015, 12, 28), matching_holiday[:date]
    assert_includes matching_holiday[:regions], :ca_on

    holidays = Holidays.on(Date.civil(2016, 12, 27), [:ca_on], [:observed])
    matching_holiday = holidays.find { |hol| hol[:name] == "Boxing Day" }
    assert_not_nil matching_holiday
    assert_equal Date.civil(2016, 12, 27), matching_holiday[:date]
    assert_includes matching_holiday[:regions], :ca_on


    assert_nil (Holidays.on(Date.civil(2015, 6, 21), [:ca_yt])[0] || {})[:name]

    assert_nil (Holidays.on(Date.civil(2016, 6, 21), [:ca_yt])[0] || {})[:name]

    holidays = Holidays.on(Date.civil(2017, 6, 21), [:ca_yt])
    matching_holiday = holidays.find { |hol| hol[:name] == "National Aboriginal Day" }
    assert_not_nil matching_holiday
    assert_equal Date.civil(2017, 6, 21), matching_holiday[:date]
    assert_includes matching_holiday[:regions], :ca_yt


    holidays = Holidays.on(Date.civil(2018, 6, 21), [:ca_yt])
    matching_holiday = holidays.find { |hol| hol[:name] == "National Aboriginal Day" }
    assert_not_nil matching_holiday
    assert_equal Date.civil(2018, 6, 21), matching_holiday[:date]
    assert_includes matching_holiday[:regions], :ca_yt


    holidays = Holidays.on(Date.civil(2013, 2, 2), [:us], [:informal])
    matching_holiday = holidays.find { |hol| hol[:name] == "Groundhog Day" }
    assert_not_nil matching_holiday
    assert_equal Date.civil(2013, 2, 2), matching_holiday[:date]
    assert_includes matching_holiday[:regions], :us


    holidays = Holidays.on(Date.civil(2013, 2, 14), [:us], [:informal])
    matching_holiday = holidays.find { |hol| hol[:name] == "Valentine's Day" }
    assert_not_nil matching_holiday
    assert_equal Date.civil(2013, 2, 14), matching_holiday[:date]
    assert_includes matching_holiday[:regions], :us


    holidays = Holidays.on(Date.civil(2013, 3, 17), [:us], [:informal])
    matching_holiday = holidays.find { |hol| hol[:name] == "St. Patrick's Day" }
    assert_not_nil matching_holiday
    assert_equal Date.civil(2013, 3, 17), matching_holiday[:date]
    assert_includes matching_holiday[:regions], :us


    holidays = Holidays.on(Date.civil(2013, 4, 1), [:us], [:informal])
    matching_holiday = holidays.find { |hol| hol[:name] == "April Fool's Day" }
    assert_not_nil matching_holiday
    assert_equal Date.civil(2013, 4, 1), matching_holiday[:date]
    assert_includes matching_holiday[:regions], :us


    holidays = Holidays.on(Date.civil(2013, 4, 22), [:us], [:informal])
    matching_holiday = holidays.find { |hol| hol[:name] == "Earth Day" }
    assert_not_nil matching_holiday
    assert_equal Date.civil(2013, 4, 22), matching_holiday[:date]
    assert_includes matching_holiday[:regions], :us


    holidays = Holidays.on(Date.civil(2013, 5, 12), [:us], [:informal])
    matching_holiday = holidays.find { |hol| hol[:name] == "Mother's Day" }
    assert_not_nil matching_holiday
    assert_equal Date.civil(2013, 5, 12), matching_holiday[:date]
    assert_includes matching_holiday[:regions], :us


    holidays = Holidays.on(Date.civil(2013, 5, 18), [:us], [:informal])
    matching_holiday = holidays.find { |hol| hol[:name] == "Armed Forces Day" }
    assert_not_nil matching_holiday
    assert_equal Date.civil(2013, 5, 18), matching_holiday[:date]
    assert_includes matching_holiday[:regions], :us


    holidays = Holidays.on(Date.civil(2013, 6, 16), [:us], [:informal])
    matching_holiday = holidays.find { |hol| hol[:name] == "Father's Day" }
    assert_not_nil matching_holiday
    assert_equal Date.civil(2013, 6, 16), matching_holiday[:date]
    assert_includes matching_holiday[:regions], :us


    holidays = Holidays.on(Date.civil(2013, 10, 31), [:us], [:informal])
    matching_holiday = holidays.find { |hol| hol[:name] == "Halloween" }
    assert_not_nil matching_holiday
    assert_equal Date.civil(2013, 10, 31), matching_holiday[:date]
    assert_includes matching_holiday[:regions], :us


  end
end
