# encoding: utf-8
require File.expand_path(File.dirname(__FILE__)) + '/../test_helper'

# This file is generated by the Ruby Holiday gem.
#
# Definitions loaded: definitions/at.yaml
class AtDefinitionTests < Test::Unit::TestCase  # :nodoc:

  def test_at
    holidays = Holidays.on(Date.civil(2009, 1, 1), [:at], [:informal])
    matching_holiday = holidays.find { |hol| hol[:name] == "Neujahrstag" }
    assert_not_nil matching_holiday
    assert_equal Date.civil(2009, 1, 1), matching_holiday[:date]
    assert_includes matching_holiday[:regions], :at


    holidays = Holidays.on(Date.civil(2009, 4, 13), [:at], [:informal])
    matching_holiday = holidays.find { |hol| hol[:name] == "Ostermontag" }
    assert_not_nil matching_holiday
    assert_equal Date.civil(2009, 4, 13), matching_holiday[:date]
    assert_includes matching_holiday[:regions], :at


    holidays = Holidays.on(Date.civil(2009, 5, 21), [:at], [:informal])
    matching_holiday = holidays.find { |hol| hol[:name] == "Christi Himmelfahrt" }
    assert_not_nil matching_holiday
    assert_equal Date.civil(2009, 5, 21), matching_holiday[:date]
    assert_includes matching_holiday[:regions], :at


    holidays = Holidays.on(Date.civil(2009, 6, 1), [:at], [:informal])
    matching_holiday = holidays.find { |hol| hol[:name] == "Pfingstmontag" }
    assert_not_nil matching_holiday
    assert_equal Date.civil(2009, 6, 1), matching_holiday[:date]
    assert_includes matching_holiday[:regions], :at


    holidays = Holidays.on(Date.civil(2009, 10, 26), [:at], [:informal])
    matching_holiday = holidays.find { |hol| hol[:name] == "Nationalfeiertag" }
    assert_not_nil matching_holiday
    assert_equal Date.civil(2009, 10, 26), matching_holiday[:date]
    assert_includes matching_holiday[:regions], :at


    holidays = Holidays.on(Date.civil(2009, 12, 8), [:at], [:informal])
    matching_holiday = holidays.find { |hol| hol[:name] == "Mariä Empfängnis" }
    assert_not_nil matching_holiday
    assert_equal Date.civil(2009, 12, 8), matching_holiday[:date]
    assert_includes matching_holiday[:regions], :at


    holidays = Holidays.on(Date.civil(2009, 12, 25), [:at], [:informal])
    matching_holiday = holidays.find { |hol| hol[:name] == "1. Weihnachtstag" }
    assert_not_nil matching_holiday
    assert_equal Date.civil(2009, 12, 25), matching_holiday[:date]
    assert_includes matching_holiday[:regions], :at


    holidays = Holidays.on(Date.civil(2009, 12, 26), [:at], [:informal])
    matching_holiday = holidays.find { |hol| hol[:name] == "2. Weihnachtstag" }
    assert_not_nil matching_holiday
    assert_equal Date.civil(2009, 12, 26), matching_holiday[:date]
    assert_includes matching_holiday[:regions], :at


    assert_nil (Holidays.on(Date.civil(2010, 5, 8), [:at])[0] || {})[:name]

  end
end
