# encoding: utf-8
require File.expand_path(File.dirname(__FILE__)) + '/../test_helper'

# This file is generated by the Ruby Holiday gem.
#
# Definitions loaded: definitions/us.yaml, definitions/north_america_informal.yaml
class UsDefinitionTests < Test::Unit::TestCase  # :nodoc:

  def test_us
    holidays = Holidays.on(Date.civil(2017, 2, 28), [:us_fl])
    matching_holiday = holidays.find { |hol| hol[:name] == "Shrove Tuesday" }
    assert_not_nil matching_holiday
    assert_equal Date.civil(2017, 2, 28), matching_holiday[:date]
    assert_includes matching_holiday[:regions], :us_fl

    holidays = Holidays.on(Date.civil(2018, 2, 13), [:us_fl])
    matching_holiday = holidays.find { |hol| hol[:name] == "Shrove Tuesday" }
    assert_not_nil matching_holiday
    assert_equal Date.civil(2018, 2, 13), matching_holiday[:date]
    assert_includes matching_holiday[:regions], :us_fl

    holidays = Holidays.on(Date.civil(2019, 3, 5), [:us_fl])
    matching_holiday = holidays.find { |hol| hol[:name] == "Shrove Tuesday" }
    assert_not_nil matching_holiday
    assert_equal Date.civil(2019, 3, 5), matching_holiday[:date]
    assert_includes matching_holiday[:regions], :us_fl


    holidays = Holidays.on(Date.civil(2017, 2, 28), [:us_la])
    matching_holiday = holidays.find { |hol| hol[:name] == "Mardi Gras Day" }
    assert_not_nil matching_holiday
    assert_equal Date.civil(2017, 2, 28), matching_holiday[:date]
    assert_includes matching_holiday[:regions], :us_la

    holidays = Holidays.on(Date.civil(2018, 2, 13), [:us_la])
    matching_holiday = holidays.find { |hol| hol[:name] == "Mardi Gras Day" }
    assert_not_nil matching_holiday
    assert_equal Date.civil(2018, 2, 13), matching_holiday[:date]
    assert_includes matching_holiday[:regions], :us_la

    holidays = Holidays.on(Date.civil(2019, 3, 5), [:us_la])
    matching_holiday = holidays.find { |hol| hol[:name] == "Mardi Gras Day" }
    assert_not_nil matching_holiday
    assert_equal Date.civil(2019, 3, 5), matching_holiday[:date]
    assert_includes matching_holiday[:regions], :us_la


    assert_nil (Holidays.on(Date.civil(2017, 2, 28), [:us])[0] || {})[:name]
    assert_nil (Holidays.on(Date.civil(2018, 2, 13), [:us])[0] || {})[:name]
    assert_nil (Holidays.on(Date.civil(2019, 3, 5), [:us])[0] || {})[:name]

    holidays = Holidays.on(Date.civil(2017, 4, 14), [:us_ct, :us_de, :us_gu, :us_hi, :us_in, :us_ky, :us_la, :us_nj, :us_nc, :us_nd, :us_pr, :us_tn])
    matching_holiday = holidays.find { |hol| hol[:name] == "Good Friday" }
    assert_not_nil matching_holiday
    assert_equal Date.civil(2017, 4, 14), matching_holiday[:date]
    assert_includes matching_holiday[:regions], :us_ct
    assert_includes matching_holiday[:regions], :us_de
    assert_includes matching_holiday[:regions], :us_gu
    assert_includes matching_holiday[:regions], :us_hi
    assert_includes matching_holiday[:regions], :us_in
    assert_includes matching_holiday[:regions], :us_ky
    assert_includes matching_holiday[:regions], :us_la
    assert_includes matching_holiday[:regions], :us_nj
    assert_includes matching_holiday[:regions], :us_nc
    assert_includes matching_holiday[:regions], :us_nd
    assert_includes matching_holiday[:regions], :us_pr
    assert_includes matching_holiday[:regions], :us_tn

    holidays = Holidays.on(Date.civil(2018, 3, 30), [:us_ct, :us_de, :us_gu, :us_hi, :us_in, :us_ky, :us_la, :us_nj, :us_nc, :us_nd, :us_pr, :us_tn])
    matching_holiday = holidays.find { |hol| hol[:name] == "Good Friday" }
    assert_not_nil matching_holiday
    assert_equal Date.civil(2018, 3, 30), matching_holiday[:date]
    assert_includes matching_holiday[:regions], :us_ct
    assert_includes matching_holiday[:regions], :us_de
    assert_includes matching_holiday[:regions], :us_gu
    assert_includes matching_holiday[:regions], :us_hi
    assert_includes matching_holiday[:regions], :us_in
    assert_includes matching_holiday[:regions], :us_ky
    assert_includes matching_holiday[:regions], :us_la
    assert_includes matching_holiday[:regions], :us_nj
    assert_includes matching_holiday[:regions], :us_nc
    assert_includes matching_holiday[:regions], :us_nd
    assert_includes matching_holiday[:regions], :us_pr
    assert_includes matching_holiday[:regions], :us_tn

    holidays = Holidays.on(Date.civil(2019, 4, 19), [:us_ct, :us_de, :us_gu, :us_hi, :us_in, :us_ky, :us_la, :us_nj, :us_nc, :us_nd, :us_pr, :us_tn])
    matching_holiday = holidays.find { |hol| hol[:name] == "Good Friday" }
    assert_not_nil matching_holiday
    assert_equal Date.civil(2019, 4, 19), matching_holiday[:date]
    assert_includes matching_holiday[:regions], :us_ct
    assert_includes matching_holiday[:regions], :us_de
    assert_includes matching_holiday[:regions], :us_gu
    assert_includes matching_holiday[:regions], :us_hi
    assert_includes matching_holiday[:regions], :us_in
    assert_includes matching_holiday[:regions], :us_ky
    assert_includes matching_holiday[:regions], :us_la
    assert_includes matching_holiday[:regions], :us_nj
    assert_includes matching_holiday[:regions], :us_nc
    assert_includes matching_holiday[:regions], :us_nd
    assert_includes matching_holiday[:regions], :us_pr
    assert_includes matching_holiday[:regions], :us_tn


    holidays = Holidays.on(Date.civil(2017, 4, 14), [:us], [:informal])
    matching_holiday = holidays.find { |hol| hol[:name] == "Good Friday" }
    assert_not_nil matching_holiday
    assert_equal Date.civil(2017, 4, 14), matching_holiday[:date]
    assert_includes matching_holiday[:regions], :us

    holidays = Holidays.on(Date.civil(2018, 3, 30), [:us], [:informal])
    matching_holiday = holidays.find { |hol| hol[:name] == "Good Friday" }
    assert_not_nil matching_holiday
    assert_equal Date.civil(2018, 3, 30), matching_holiday[:date]
    assert_includes matching_holiday[:regions], :us

    holidays = Holidays.on(Date.civil(2019, 4, 19), [:us], [:informal])
    matching_holiday = holidays.find { |hol| hol[:name] == "Good Friday" }
    assert_not_nil matching_holiday
    assert_equal Date.civil(2019, 4, 19), matching_holiday[:date]
    assert_includes matching_holiday[:regions], :us


    assert_nil (Holidays.on(Date.civil(2017, 2, 28), [:us])[0] || {})[:name]
    assert_nil (Holidays.on(Date.civil(2018, 2, 13), [:us])[0] || {})[:name]
    assert_nil (Holidays.on(Date.civil(2019, 3, 5), [:us])[0] || {})[:name]

    assert_nil (Holidays.on(Date.civil(2017, 4, 16), [:us])[0] || {})[:name]
    assert_nil (Holidays.on(Date.civil(2018, 4, 1), [:us])[0] || {})[:name]
    assert_nil (Holidays.on(Date.civil(2019, 4, 21), [:us])[0] || {})[:name]

    holidays = Holidays.on(Date.civil(2017, 4, 16), [:us], [:informal])
    matching_holiday = holidays.find { |hol| hol[:name] == "Easter Sunday" }
    assert_not_nil matching_holiday
    assert_equal Date.civil(2017, 4, 16), matching_holiday[:date]
    assert_includes matching_holiday[:regions], :us

    holidays = Holidays.on(Date.civil(2018, 4, 1), [:us], [:informal])
    matching_holiday = holidays.find { |hol| hol[:name] == "Easter Sunday" }
    assert_not_nil matching_holiday
    assert_equal Date.civil(2018, 4, 1), matching_holiday[:date]
    assert_includes matching_holiday[:regions], :us

    holidays = Holidays.on(Date.civil(2019, 4, 21), [:us], [:informal])
    matching_holiday = holidays.find { |hol| hol[:name] == "Easter Sunday" }
    assert_not_nil matching_holiday
    assert_equal Date.civil(2019, 4, 21), matching_holiday[:date]
    assert_includes matching_holiday[:regions], :us


    holidays = Holidays.on(Date.civil(2017, 1, 1), [:us])
    matching_holiday = holidays.find { |hol| hol[:name] == "New Year's Day" }
    assert_not_nil matching_holiday
    assert_equal Date.civil(2017, 1, 1), matching_holiday[:date]
    assert_includes matching_holiday[:regions], :us


    holidays = Holidays.on(Date.civil(2017, 1, 2), [:us], [:observed])
    matching_holiday = holidays.find { |hol| hol[:name] == "New Year's Day" }
    assert_not_nil matching_holiday
    assert_equal Date.civil(2017, 1, 2), matching_holiday[:date]
    assert_includes matching_holiday[:regions], :us


    holidays = Holidays.on(Date.civil(2017, 1, 16), [:us])
    matching_holiday = holidays.find { |hol| hol[:name] == "Martin Luther King Jr. Day" }
    assert_not_nil matching_holiday
    assert_equal Date.civil(2017, 1, 16), matching_holiday[:date]
    assert_includes matching_holiday[:regions], :us

    holidays = Holidays.on(Date.civil(2018, 1, 15), [:us])
    matching_holiday = holidays.find { |hol| hol[:name] == "Martin Luther King Jr. Day" }
    assert_not_nil matching_holiday
    assert_equal Date.civil(2018, 1, 15), matching_holiday[:date]
    assert_includes matching_holiday[:regions], :us

    holidays = Holidays.on(Date.civil(2019, 1, 21), [:us])
    matching_holiday = holidays.find { |hol| hol[:name] == "Martin Luther King Jr. Day" }
    assert_not_nil matching_holiday
    assert_equal Date.civil(2019, 1, 21), matching_holiday[:date]
    assert_includes matching_holiday[:regions], :us


    holidays = Holidays.on(Date.civil(2016, 1, 18), [:us])
    matching_holiday = holidays.find { |hol| hol[:name] == "Martin Luther King Jr. Day" }
    assert_not_nil matching_holiday
    assert_equal Date.civil(2016, 1, 18), matching_holiday[:date]
    assert_includes matching_holiday[:regions], :us

    holidays = Holidays.on(Date.civil(2017, 1, 16), [:us])
    matching_holiday = holidays.find { |hol| hol[:name] == "Martin Luther King Jr. Day" }
    assert_not_nil matching_holiday
    assert_equal Date.civil(2017, 1, 16), matching_holiday[:date]
    assert_includes matching_holiday[:regions], :us

    holidays = Holidays.on(Date.civil(2018, 1, 15), [:us])
    matching_holiday = holidays.find { |hol| hol[:name] == "Martin Luther King Jr. Day" }
    assert_not_nil matching_holiday
    assert_equal Date.civil(2018, 1, 15), matching_holiday[:date]
    assert_includes matching_holiday[:regions], :us


    holidays = Holidays.on(Date.civil(2016, 1, 18), [:us_ms])
    matching_holiday = holidays.find { |hol| hol[:name] == "Martin Luther King's and Robert E. Lee's Birthdays" }
    assert_not_nil matching_holiday
    assert_equal Date.civil(2016, 1, 18), matching_holiday[:date]
    assert_includes matching_holiday[:regions], :us_ms

    holidays = Holidays.on(Date.civil(2017, 1, 16), [:us_ms])
    matching_holiday = holidays.find { |hol| hol[:name] == "Martin Luther King's and Robert E. Lee's Birthdays" }
    assert_not_nil matching_holiday
    assert_equal Date.civil(2017, 1, 16), matching_holiday[:date]
    assert_includes matching_holiday[:regions], :us_ms

    holidays = Holidays.on(Date.civil(2018, 1, 15), [:us_ms])
    matching_holiday = holidays.find { |hol| hol[:name] == "Martin Luther King's and Robert E. Lee's Birthdays" }
    assert_not_nil matching_holiday
    assert_equal Date.civil(2018, 1, 15), matching_holiday[:date]
    assert_includes matching_holiday[:regions], :us_ms


    holidays = Holidays.on(Date.civil(2016, 1, 18), [:us_id])
    matching_holiday = holidays.find { |hol| hol[:name] == "Idaho Human Rights Day" }
    assert_not_nil matching_holiday
    assert_equal Date.civil(2016, 1, 18), matching_holiday[:date]
    assert_includes matching_holiday[:regions], :us_id

    holidays = Holidays.on(Date.civil(2017, 1, 16), [:us_id])
    matching_holiday = holidays.find { |hol| hol[:name] == "Idaho Human Rights Day" }
    assert_not_nil matching_holiday
    assert_equal Date.civil(2017, 1, 16), matching_holiday[:date]
    assert_includes matching_holiday[:regions], :us_id

    holidays = Holidays.on(Date.civil(2018, 1, 15), [:us_id])
    matching_holiday = holidays.find { |hol| hol[:name] == "Idaho Human Rights Day" }
    assert_not_nil matching_holiday
    assert_equal Date.civil(2018, 1, 15), matching_holiday[:date]
    assert_includes matching_holiday[:regions], :us_id


    holidays = Holidays.on(Date.civil(2016, 1, 18), [:us_ar])
    matching_holiday = holidays.find { |hol| hol[:name] == "Civil Rights Day" }
    assert_not_nil matching_holiday
    assert_equal Date.civil(2016, 1, 18), matching_holiday[:date]
    assert_includes matching_holiday[:regions], :us_ar

    holidays = Holidays.on(Date.civil(2017, 1, 16), [:us_ar])
    matching_holiday = holidays.find { |hol| hol[:name] == "Civil Rights Day" }
    assert_not_nil matching_holiday
    assert_equal Date.civil(2017, 1, 16), matching_holiday[:date]
    assert_includes matching_holiday[:regions], :us_ar

    holidays = Holidays.on(Date.civil(2018, 1, 15), [:us_ar])
    matching_holiday = holidays.find { |hol| hol[:name] == "Civil Rights Day" }
    assert_not_nil matching_holiday
    assert_equal Date.civil(2018, 1, 15), matching_holiday[:date]
    assert_includes matching_holiday[:regions], :us_ar


    assert_nil (Holidays.on(Date.civil(2017, 1, 20), [:us])[0] || {})[:name]
    assert_nil (Holidays.on(Date.civil(2021, 1, 20), [:us])[0] || {})[:name]

    holidays = Holidays.on(Date.civil(2017, 1, 20), [:us_tx, :us_dc, :us_la, :us_md, :us_va])
    matching_holiday = holidays.find { |hol| hol[:name] == "Inauguration Day" }
    assert_not_nil matching_holiday
    assert_equal Date.civil(2017, 1, 20), matching_holiday[:date]
    assert_includes matching_holiday[:regions], :us_tx
    assert_includes matching_holiday[:regions], :us_dc
    assert_includes matching_holiday[:regions], :us_la
    assert_includes matching_holiday[:regions], :us_md
    assert_includes matching_holiday[:regions], :us_va

    holidays = Holidays.on(Date.civil(2021, 1, 20), [:us_tx, :us_dc, :us_la, :us_md, :us_va])
    matching_holiday = holidays.find { |hol| hol[:name] == "Inauguration Day" }
    assert_not_nil matching_holiday
    assert_equal Date.civil(2021, 1, 20), matching_holiday[:date]
    assert_includes matching_holiday[:regions], :us_tx
    assert_includes matching_holiday[:regions], :us_dc
    assert_includes matching_holiday[:regions], :us_la
    assert_includes matching_holiday[:regions], :us_md
    assert_includes matching_holiday[:regions], :us_va


    assert_nil (Holidays.on(Date.civil(2017, 1, 13), [:us])[0] || {})[:name]
    assert_nil (Holidays.on(Date.civil(2018, 1, 12), [:us])[0] || {})[:name]
    assert_nil (Holidays.on(Date.civil(2019, 1, 18), [:us])[0] || {})[:name]

    holidays = Holidays.on(Date.civil(2017, 1, 13), [:us_va])
    matching_holiday = holidays.find { |hol| hol[:name] == "Lee-Jackson Day" }
    assert_not_nil matching_holiday
    assert_equal Date.civil(2017, 1, 13), matching_holiday[:date]
    assert_includes matching_holiday[:regions], :us_va

    holidays = Holidays.on(Date.civil(2018, 1, 12), [:us_va])
    matching_holiday = holidays.find { |hol| hol[:name] == "Lee-Jackson Day" }
    assert_not_nil matching_holiday
    assert_equal Date.civil(2018, 1, 12), matching_holiday[:date]
    assert_includes matching_holiday[:regions], :us_va

    holidays = Holidays.on(Date.civil(2019, 1, 18), [:us_va])
    matching_holiday = holidays.find { |hol| hol[:name] == "Lee-Jackson Day" }
    assert_not_nil matching_holiday
    assert_equal Date.civil(2019, 1, 18), matching_holiday[:date]
    assert_includes matching_holiday[:regions], :us_va


    holidays = Holidays.on(Date.civil(2017, 1, 19), [:us_tx])
    matching_holiday = holidays.find { |hol| hol[:name] == "Confederate Heroes Day" }
    assert_not_nil matching_holiday
    assert_equal Date.civil(2017, 1, 19), matching_holiday[:date]
    assert_includes matching_holiday[:regions], :us_tx


    holidays = Holidays.on(Date.civil(2008, 2, 18), [:us])
    matching_holiday = holidays.find { |hol| hol[:name] == "Presidents' Day" }
    assert_not_nil matching_holiday
    assert_equal Date.civil(2008, 2, 18), matching_holiday[:date]
    assert_includes matching_holiday[:regions], :us

    holidays = Holidays.on(Date.civil(2017, 2, 20), [:us])
    matching_holiday = holidays.find { |hol| hol[:name] == "Presidents' Day" }
    assert_not_nil matching_holiday
    assert_equal Date.civil(2017, 2, 20), matching_holiday[:date]
    assert_includes matching_holiday[:regions], :us

    holidays = Holidays.on(Date.civil(2018, 2, 19), [:us])
    matching_holiday = holidays.find { |hol| hol[:name] == "Presidents' Day" }
    assert_not_nil matching_holiday
    assert_equal Date.civil(2018, 2, 19), matching_holiday[:date]
    assert_includes matching_holiday[:regions], :us


    assert_nil (Holidays.on(Date.civil(2017, 3, 6), [:us])[0] || {})[:name]
    assert_nil (Holidays.on(Date.civil(2018, 3, 5), [:us])[0] || {})[:name]
    assert_nil (Holidays.on(Date.civil(2019, 3, 4), [:us])[0] || {})[:name]

    assert_nil (Holidays.on(Date.civil(2017, 3, 7), [:us])[0] || {})[:name]
    assert_nil (Holidays.on(Date.civil(2018, 3, 6), [:us])[0] || {})[:name]
    assert_nil (Holidays.on(Date.civil(2019, 3, 5), [:us])[0] || {})[:name]

    holidays = Holidays.on(Date.civil(2017, 3, 7), [:us_vt])
    matching_holiday = holidays.find { |hol| hol[:name] == "Town Meeting Day" }
    assert_not_nil matching_holiday
    assert_equal Date.civil(2017, 3, 7), matching_holiday[:date]
    assert_includes matching_holiday[:regions], :us_vt

    holidays = Holidays.on(Date.civil(2018, 3, 6), [:us_vt])
    matching_holiday = holidays.find { |hol| hol[:name] == "Town Meeting Day" }
    assert_not_nil matching_holiday
    assert_equal Date.civil(2018, 3, 6), matching_holiday[:date]
    assert_includes matching_holiday[:regions], :us_vt

    holidays = Holidays.on(Date.civil(2019, 3, 5), [:us_vt])
    matching_holiday = holidays.find { |hol| hol[:name] == "Town Meeting Day" }
    assert_not_nil matching_holiday
    assert_equal Date.civil(2019, 3, 5), matching_holiday[:date]
    assert_includes matching_holiday[:regions], :us_vt


    holidays = Holidays.on(Date.civil(2017, 3, 2), [:us_tx])
    matching_holiday = holidays.find { |hol| hol[:name] == "Texas Independence Day" }
    assert_not_nil matching_holiday
    assert_equal Date.civil(2017, 3, 2), matching_holiday[:date]
    assert_includes matching_holiday[:regions], :us_tx


    assert_nil (Holidays.on(Date.civil(2017, 3, 27), [:us], [:observed])[0] || {})[:name]
    assert_nil (Holidays.on(Date.civil(2018, 3, 26), [:us], [:observed])[0] || {})[:name]
    assert_nil (Holidays.on(Date.civil(2022, 3, 25), [:us], [:observed])[0] || {})[:name]

    holidays = Holidays.on(Date.civil(2017, 3, 27), [:us_hi], [:observed])
    matching_holiday = holidays.find { |hol| hol[:name] == "Prince Jonah Kuhio Kalanianaole Day" }
    assert_not_nil matching_holiday
    assert_equal Date.civil(2017, 3, 27), matching_holiday[:date]
    assert_includes matching_holiday[:regions], :us_hi

    holidays = Holidays.on(Date.civil(2018, 3, 26), [:us_hi], [:observed])
    matching_holiday = holidays.find { |hol| hol[:name] == "Prince Jonah Kuhio Kalanianaole Day" }
    assert_not_nil matching_holiday
    assert_equal Date.civil(2018, 3, 26), matching_holiday[:date]
    assert_includes matching_holiday[:regions], :us_hi

    holidays = Holidays.on(Date.civil(2022, 3, 25), [:us_hi], [:observed])
    matching_holiday = holidays.find { |hol| hol[:name] == "Prince Jonah Kuhio Kalanianaole Day" }
    assert_not_nil matching_holiday
    assert_equal Date.civil(2022, 3, 25), matching_holiday[:date]
    assert_includes matching_holiday[:regions], :us_hi


    assert_nil (Holidays.on(Date.civil(2017, 3, 26), [:us])[0] || {})[:name]

    holidays = Holidays.on(Date.civil(2017, 3, 26), [:us_hi])
    matching_holiday = holidays.find { |hol| hol[:name] == "Prince Jonah Kuhio Kalanianaole Day" }
    assert_not_nil matching_holiday
    assert_equal Date.civil(2017, 3, 26), matching_holiday[:date]
    assert_includes matching_holiday[:regions], :us_hi


    assert_nil (Holidays.on(Date.civil(2017, 3, 27), [:us])[0] || {})[:name]
    assert_nil (Holidays.on(Date.civil(2018, 3, 26), [:us])[0] || {})[:name]
    assert_nil (Holidays.on(Date.civil(2019, 3, 25), [:us])[0] || {})[:name]

    holidays = Holidays.on(Date.civil(2017, 3, 27), [:us_ak])
    matching_holiday = holidays.find { |hol| hol[:name] == "Seward's Day" }
    assert_not_nil matching_holiday
    assert_equal Date.civil(2017, 3, 27), matching_holiday[:date]
    assert_includes matching_holiday[:regions], :us_ak

    holidays = Holidays.on(Date.civil(2018, 3, 26), [:us_ak])
    matching_holiday = holidays.find { |hol| hol[:name] == "Seward's Day" }
    assert_not_nil matching_holiday
    assert_equal Date.civil(2018, 3, 26), matching_holiday[:date]
    assert_includes matching_holiday[:regions], :us_ak

    holidays = Holidays.on(Date.civil(2019, 3, 25), [:us_ak])
    matching_holiday = holidays.find { |hol| hol[:name] == "Seward's Day" }
    assert_not_nil matching_holiday
    assert_equal Date.civil(2019, 3, 25), matching_holiday[:date]
    assert_includes matching_holiday[:regions], :us_ak


    holidays = Holidays.on(Date.civil(2017, 3, 31), [:us_ca])
    matching_holiday = holidays.find { |hol| hol[:name] == "César Chávez Day" }
    assert_not_nil matching_holiday
    assert_equal Date.civil(2017, 3, 31), matching_holiday[:date]
    assert_includes matching_holiday[:regions], :us_ca


    holidays = Holidays.on(Date.civil(2023, 4, 17), [:us_dc, :us_ca], [:observed])
    matching_holiday = holidays.find { |hol| hol[:name] == "Emancipation Day" }
    assert_not_nil matching_holiday
    assert_equal Date.civil(2023, 4, 17), matching_holiday[:date]
    assert_includes matching_holiday[:regions], :us_dc
    assert_includes matching_holiday[:regions], :us_ca

    holidays = Holidays.on(Date.civil(2022, 4, 15), [:us_dc, :us_ca], [:observed])
    matching_holiday = holidays.find { |hol| hol[:name] == "Emancipation Day" }
    assert_not_nil matching_holiday
    assert_equal Date.civil(2022, 4, 15), matching_holiday[:date]
    assert_includes matching_holiday[:regions], :us_dc
    assert_includes matching_holiday[:regions], :us_ca

    holidays = Holidays.on(Date.civil(2028, 4, 17), [:us_dc, :us_ca], [:observed])
    matching_holiday = holidays.find { |hol| hol[:name] == "Emancipation Day" }
    assert_not_nil matching_holiday
    assert_equal Date.civil(2028, 4, 17), matching_holiday[:date]
    assert_includes matching_holiday[:regions], :us_dc
    assert_includes matching_holiday[:regions], :us_ca


    holidays = Holidays.on(Date.civil(2017, 4, 16), [:us_dc])
    matching_holiday = holidays.find { |hol| hol[:name] == "Emancipation Day" }
    assert_not_nil matching_holiday
    assert_equal Date.civil(2017, 4, 16), matching_holiday[:date]
    assert_includes matching_holiday[:regions], :us_dc


    assert_nil (Holidays.on(Date.civil(2017, 4, 17), [:us])[0] || {})[:name]
    assert_nil (Holidays.on(Date.civil(2018, 4, 16), [:us])[0] || {})[:name]
    assert_nil (Holidays.on(Date.civil(2019, 4, 15), [:us])[0] || {})[:name]

    holidays = Holidays.on(Date.civil(2017, 4, 17), [:us_me, :us_ma])
    matching_holiday = holidays.find { |hol| hol[:name] == "Patriots' Day" }
    assert_not_nil matching_holiday
    assert_equal Date.civil(2017, 4, 17), matching_holiday[:date]
    assert_includes matching_holiday[:regions], :us_me
    assert_includes matching_holiday[:regions], :us_ma

    holidays = Holidays.on(Date.civil(2018, 4, 16), [:us_me, :us_ma])
    matching_holiday = holidays.find { |hol| hol[:name] == "Patriots' Day" }
    assert_not_nil matching_holiday
    assert_equal Date.civil(2018, 4, 16), matching_holiday[:date]
    assert_includes matching_holiday[:regions], :us_me
    assert_includes matching_holiday[:regions], :us_ma

    holidays = Holidays.on(Date.civil(2019, 4, 15), [:us_me, :us_ma])
    matching_holiday = holidays.find { |hol| hol[:name] == "Patriots' Day" }
    assert_not_nil matching_holiday
    assert_equal Date.civil(2019, 4, 15), matching_holiday[:date]
    assert_includes matching_holiday[:regions], :us_me
    assert_includes matching_holiday[:regions], :us_ma


    holidays = Holidays.on(Date.civil(2017, 4, 21), [:us_tx])
    matching_holiday = holidays.find { |hol| hol[:name] == "San Jacinto Day" }
    assert_not_nil matching_holiday
    assert_equal Date.civil(2017, 4, 21), matching_holiday[:date]
    assert_includes matching_holiday[:regions], :us_tx


    assert_nil (Holidays.on(Date.civil(2017, 4, 24), [:us])[0] || {})[:name]
    assert_nil (Holidays.on(Date.civil(2018, 4, 30), [:us])[0] || {})[:name]
    assert_nil (Holidays.on(Date.civil(2019, 4, 29), [:us])[0] || {})[:name]

    holidays = Holidays.on(Date.civil(2017, 4, 24), [:us_al, :us_ms])
    matching_holiday = holidays.find { |hol| hol[:name] == "Confederate Memorial Day" }
    assert_not_nil matching_holiday
    assert_equal Date.civil(2017, 4, 24), matching_holiday[:date]
    assert_includes matching_holiday[:regions], :us_al
    assert_includes matching_holiday[:regions], :us_ms

    holidays = Holidays.on(Date.civil(2018, 4, 30), [:us_al, :us_ms])
    matching_holiday = holidays.find { |hol| hol[:name] == "Confederate Memorial Day" }
    assert_not_nil matching_holiday
    assert_equal Date.civil(2018, 4, 30), matching_holiday[:date]
    assert_includes matching_holiday[:regions], :us_al
    assert_includes matching_holiday[:regions], :us_ms

    holidays = Holidays.on(Date.civil(2019, 4, 29), [:us_al, :us_ms])
    matching_holiday = holidays.find { |hol| hol[:name] == "Confederate Memorial Day" }
    assert_not_nil matching_holiday
    assert_equal Date.civil(2019, 4, 29), matching_holiday[:date]
    assert_includes matching_holiday[:regions], :us_al
    assert_includes matching_holiday[:regions], :us_ms


    assert_nil (Holidays.on(Date.civil(2015, 4, 27), [:us])[0] || {})[:name]
    assert_nil (Holidays.on(Date.civil(2020, 4, 27), [:us])[0] || {})[:name]
    assert_nil (Holidays.on(Date.civil(2026, 4, 27), [:us])[0] || {})[:name]

    holidays = Holidays.on(Date.civil(2015, 4, 27), [:us_fl], [:observed])
    matching_holiday = holidays.find { |hol| hol[:name] == "Confederate Memorial Day" }
    assert_not_nil matching_holiday
    assert_equal Date.civil(2015, 4, 27), matching_holiday[:date]
    assert_includes matching_holiday[:regions], :us_fl

    holidays = Holidays.on(Date.civil(2020, 4, 27), [:us_fl], [:observed])
    matching_holiday = holidays.find { |hol| hol[:name] == "Confederate Memorial Day" }
    assert_not_nil matching_holiday
    assert_equal Date.civil(2020, 4, 27), matching_holiday[:date]
    assert_includes matching_holiday[:regions], :us_fl

    holidays = Holidays.on(Date.civil(2026, 4, 27), [:us_fl], [:observed])
    matching_holiday = holidays.find { |hol| hol[:name] == "Confederate Memorial Day" }
    assert_not_nil matching_holiday
    assert_equal Date.civil(2026, 4, 27), matching_holiday[:date]
    assert_includes matching_holiday[:regions], :us_fl


    assert_nil (Holidays.on(Date.civil(2017, 4, 26), [:us])[0] || {})[:name]

    holidays = Holidays.on(Date.civil(2017, 4, 26), [:us_fl])
    matching_holiday = holidays.find { |hol| hol[:name] == "Confederate Memorial Day" }
    assert_not_nil matching_holiday
    assert_equal Date.civil(2017, 4, 26), matching_holiday[:date]
    assert_includes matching_holiday[:regions], :us_fl


    assert_nil (Holidays.on(Date.civil(2015, 4, 20), [:us])[0] || {})[:name]
    assert_nil (Holidays.on(Date.civil(2021, 4, 26), [:us])[0] || {})[:name]

    holidays = Holidays.on(Date.civil(2015, 4, 20), [:us_ga])
    matching_holiday = holidays.find { |hol| hol[:name] == "State Holiday" }
    assert_not_nil matching_holiday
    assert_equal Date.civil(2015, 4, 20), matching_holiday[:date]
    assert_includes matching_holiday[:regions], :us_ga

    holidays = Holidays.on(Date.civil(2021, 4, 26), [:us_ga])
    matching_holiday = holidays.find { |hol| hol[:name] == "State Holiday" }
    assert_not_nil matching_holiday
    assert_equal Date.civil(2021, 4, 26), matching_holiday[:date]
    assert_includes matching_holiday[:regions], :us_ga


    holidays = Holidays.on(Date.civil(2017, 4, 28), [:us_ne])
    matching_holiday = holidays.find { |hol| hol[:name] == "Arbor Day" }
    assert_not_nil matching_holiday
    assert_equal Date.civil(2017, 4, 28), matching_holiday[:date]
    assert_includes matching_holiday[:regions], :us_ne


    holidays = Holidays.on(Date.civil(2017, 5, 8), [:us_mo])
    matching_holiday = holidays.find { |hol| hol[:name] == "Truman Day" }
    assert_not_nil matching_holiday
    assert_equal Date.civil(2017, 5, 8), matching_holiday[:date]
    assert_includes matching_holiday[:regions], :us_mo


    holidays = Holidays.on(Date.civil(2017, 5, 10), [:us_sc])
    matching_holiday = holidays.find { |hol| hol[:name] == "Confederate Memorial Day" }
    assert_not_nil matching_holiday
    assert_equal Date.civil(2017, 5, 10), matching_holiday[:date]
    assert_includes matching_holiday[:regions], :us_sc


    holidays = Holidays.on(Date.civil(2017, 5, 29), [:us])
    matching_holiday = holidays.find { |hol| hol[:name] == "Memorial Day" }
    assert_not_nil matching_holiday
    assert_equal Date.civil(2017, 5, 29), matching_holiday[:date]
    assert_includes matching_holiday[:regions], :us

    holidays = Holidays.on(Date.civil(2018, 5, 28), [:us])
    matching_holiday = holidays.find { |hol| hol[:name] == "Memorial Day" }
    assert_not_nil matching_holiday
    assert_equal Date.civil(2018, 5, 28), matching_holiday[:date]
    assert_includes matching_holiday[:regions], :us

    holidays = Holidays.on(Date.civil(2019, 5, 27), [:us])
    matching_holiday = holidays.find { |hol| hol[:name] == "Memorial Day" }
    assert_not_nil matching_holiday
    assert_equal Date.civil(2019, 5, 27), matching_holiday[:date]
    assert_includes matching_holiday[:regions], :us


    assert_nil (Holidays.on(Date.civil(2017, 6, 5), [:us])[0] || {})[:name]
    assert_nil (Holidays.on(Date.civil(2018, 6, 4), [:us])[0] || {})[:name]
    assert_nil (Holidays.on(Date.civil(2019, 6, 3), [:us])[0] || {})[:name]

    holidays = Holidays.on(Date.civil(2017, 6, 5), [:us_al])
    matching_holiday = holidays.find { |hol| hol[:name] == "Jefferson Davis' Birthday" }
    assert_not_nil matching_holiday
    assert_equal Date.civil(2017, 6, 5), matching_holiday[:date]
    assert_includes matching_holiday[:regions], :us_al

    holidays = Holidays.on(Date.civil(2018, 6, 4), [:us_al])
    matching_holiday = holidays.find { |hol| hol[:name] == "Jefferson Davis' Birthday" }
    assert_not_nil matching_holiday
    assert_equal Date.civil(2018, 6, 4), matching_holiday[:date]
    assert_includes matching_holiday[:regions], :us_al

    holidays = Holidays.on(Date.civil(2019, 6, 3), [:us_al])
    matching_holiday = holidays.find { |hol| hol[:name] == "Jefferson Davis' Birthday" }
    assert_not_nil matching_holiday
    assert_equal Date.civil(2019, 6, 3), matching_holiday[:date]
    assert_includes matching_holiday[:regions], :us_al


    holidays = Holidays.on(Date.civil(2017, 6, 3), [:us_fl])
    matching_holiday = holidays.find { |hol| hol[:name] == "Birthday of Jefferson Davis" }
    assert_not_nil matching_holiday
    assert_equal Date.civil(2017, 6, 3), matching_holiday[:date]
    assert_includes matching_holiday[:regions], :us_fl


    assert_nil (Holidays.on(Date.civil(2017, 6, 12), [:us])[0] || {})[:name]
    assert_nil (Holidays.on(Date.civil(2018, 6, 11), [:us])[0] || {})[:name]
    assert_nil (Holidays.on(Date.civil(2022, 6, 10), [:us])[0] || {})[:name]

    holidays = Holidays.on(Date.civil(2017, 6, 12), [:us_hi], [:observed])
    matching_holiday = holidays.find { |hol| hol[:name] == "King Kamehameha I Day" }
    assert_not_nil matching_holiday
    assert_equal Date.civil(2017, 6, 12), matching_holiday[:date]
    assert_includes matching_holiday[:regions], :us_hi

    holidays = Holidays.on(Date.civil(2018, 6, 11), [:us_hi], [:observed])
    matching_holiday = holidays.find { |hol| hol[:name] == "King Kamehameha I Day" }
    assert_not_nil matching_holiday
    assert_equal Date.civil(2018, 6, 11), matching_holiday[:date]
    assert_includes matching_holiday[:regions], :us_hi

    holidays = Holidays.on(Date.civil(2022, 6, 10), [:us_hi], [:observed])
    matching_holiday = holidays.find { |hol| hol[:name] == "King Kamehameha I Day" }
    assert_not_nil matching_holiday
    assert_equal Date.civil(2022, 6, 10), matching_holiday[:date]
    assert_includes matching_holiday[:regions], :us_hi


    assert_nil (Holidays.on(Date.civil(2017, 6, 11), [:us])[0] || {})[:name]

    holidays = Holidays.on(Date.civil(2017, 6, 11), [:us_hi])
    matching_holiday = holidays.find { |hol| hol[:name] == "King Kamehameha I Day" }
    assert_not_nil matching_holiday
    assert_equal Date.civil(2017, 6, 11), matching_holiday[:date]
    assert_includes matching_holiday[:regions], :us_hi


    holidays = Holidays.on(Date.civil(2017, 6, 19), [:us_tx])
    matching_holiday = holidays.find { |hol| hol[:name] == "Emancipation Day in Texas" }
    assert_not_nil matching_holiday
    assert_equal Date.civil(2017, 6, 19), matching_holiday[:date]
    assert_includes matching_holiday[:regions], :us_tx


    assert_nil (Holidays.on(Date.civil(2017, 6, 20), [:us])[0] || {})[:name]
    assert_nil (Holidays.on(Date.civil(2020, 6, 19), [:us])[0] || {})[:name]
    assert_nil (Holidays.on(Date.civil(2021, 6, 21), [:us])[0] || {})[:name]

    holidays = Holidays.on(Date.civil(2021, 6, 18), [:us], [:observed])
    matching_holiday = holidays.find { |hol| hol[:name] == "Juneteenth National Independence Day" }
    assert_not_nil matching_holiday
    assert_equal Date.civil(2021, 6, 18), matching_holiday[:date]
    assert_includes matching_holiday[:regions], :us


    holidays = Holidays.on(Date.civil(2017, 6, 20), [:us_wv], [:observed])
    matching_holiday = holidays.find { |hol| hol[:name] == "West Virginia Day" }
    assert_not_nil matching_holiday
    assert_equal Date.civil(2017, 6, 20), matching_holiday[:date]
    assert_includes matching_holiday[:regions], :us_wv

    holidays = Holidays.on(Date.civil(2020, 6, 19), [:us_wv], [:observed])
    matching_holiday = holidays.find { |hol| hol[:name] == "West Virginia Day" }
    assert_not_nil matching_holiday
    assert_equal Date.civil(2020, 6, 19), matching_holiday[:date]
    assert_includes matching_holiday[:regions], :us_wv

    holidays = Holidays.on(Date.civil(2021, 6, 21), [:us_wv], [:observed])
    matching_holiday = holidays.find { |hol| hol[:name] == "West Virginia Day" }
    assert_not_nil matching_holiday
    assert_equal Date.civil(2021, 6, 21), matching_holiday[:date]
    assert_includes matching_holiday[:regions], :us_wv


    holidays = Holidays.on(Date.civil(2017, 6, 20), [:us_wv])
    matching_holiday = holidays.find { |hol| hol[:name] == "West Virginia Day" }
    assert_not_nil matching_holiday
    assert_equal Date.civil(2017, 6, 20), matching_holiday[:date]
    assert_includes matching_holiday[:regions], :us_wv


    holidays = Holidays.on(Date.civil(2017, 7, 3), [:us_vi])
    matching_holiday = holidays.find { |hol| hol[:name] == "Emancipation Day" }
    assert_not_nil matching_holiday
    assert_equal Date.civil(2017, 7, 3), matching_holiday[:date]
    assert_includes matching_holiday[:regions], :us_vi


    holidays = Holidays.on(Date.civil(2020, 7, 4), [:us, :us_va])
    matching_holiday = holidays.find { |hol| hol[:name] == "Independence Day" }
    assert_not_nil matching_holiday
    assert_equal Date.civil(2020, 7, 4), matching_holiday[:date]
    assert_includes matching_holiday[:regions], :us
    assert_includes matching_holiday[:regions], :us_va

    holidays = Holidays.on(Date.civil(2021, 7, 4), [:us, :us_va])
    matching_holiday = holidays.find { |hol| hol[:name] == "Independence Day" }
    assert_not_nil matching_holiday
    assert_equal Date.civil(2021, 7, 4), matching_holiday[:date]
    assert_includes matching_holiday[:regions], :us
    assert_includes matching_holiday[:regions], :us_va

    holidays = Holidays.on(Date.civil(2026, 7, 4), [:us, :us_va])
    matching_holiday = holidays.find { |hol| hol[:name] == "Independence Day" }
    assert_not_nil matching_holiday
    assert_equal Date.civil(2026, 7, 4), matching_holiday[:date]
    assert_includes matching_holiday[:regions], :us
    assert_includes matching_holiday[:regions], :us_va


    assert_nil (Holidays.on(Date.civil(2020, 7, 3), [:us])[0] || {})[:name]
    assert_nil (Holidays.on(Date.civil(2021, 7, 5), [:us])[0] || {})[:name]
    assert_nil (Holidays.on(Date.civil(2026, 7, 3), [:us])[0] || {})[:name]

    holidays = Holidays.on(Date.civil(2020, 7, 3), [:us_va])
    matching_holiday = holidays.find { |hol| hol[:name] == "Independence Day (Holiday)" }
    assert_not_nil matching_holiday
    assert_equal Date.civil(2020, 7, 3), matching_holiday[:date]
    assert_includes matching_holiday[:regions], :us_va

    holidays = Holidays.on(Date.civil(2021, 7, 5), [:us_va])
    matching_holiday = holidays.find { |hol| hol[:name] == "Independence Day (Holiday)" }
    assert_not_nil matching_holiday
    assert_equal Date.civil(2021, 7, 5), matching_holiday[:date]
    assert_includes matching_holiday[:regions], :us_va

    holidays = Holidays.on(Date.civil(2026, 7, 3), [:us_va])
    matching_holiday = holidays.find { |hol| hol[:name] == "Independence Day (Holiday)" }
    assert_not_nil matching_holiday
    assert_equal Date.civil(2026, 7, 3), matching_holiday[:date]
    assert_includes matching_holiday[:regions], :us_va


    holidays = Holidays.on(Date.civil(2020, 7, 24), [:us_ut])
    matching_holiday = holidays.find { |hol| hol[:name] == "Pioneer Day" }
    assert_not_nil matching_holiday
    assert_equal Date.civil(2020, 7, 24), matching_holiday[:date]
    assert_includes matching_holiday[:regions], :us_ut


    assert_nil (Holidays.on(Date.civil(2017, 8, 14), [:us])[0] || {})[:name]
    assert_nil (Holidays.on(Date.civil(2020, 8, 10), [:us])[0] || {})[:name]
    assert_nil (Holidays.on(Date.civil(2021, 8, 9), [:us])[0] || {})[:name]

    holidays = Holidays.on(Date.civil(2017, 8, 14), [:us_ri])
    matching_holiday = holidays.find { |hol| hol[:name] == "Victory Day" }
    assert_not_nil matching_holiday
    assert_equal Date.civil(2017, 8, 14), matching_holiday[:date]
    assert_includes matching_holiday[:regions], :us_ri

    holidays = Holidays.on(Date.civil(2020, 8, 10), [:us_ri])
    matching_holiday = holidays.find { |hol| hol[:name] == "Victory Day" }
    assert_not_nil matching_holiday
    assert_equal Date.civil(2020, 8, 10), matching_holiday[:date]
    assert_includes matching_holiday[:regions], :us_ri

    holidays = Holidays.on(Date.civil(2021, 8, 9), [:us_ri])
    matching_holiday = holidays.find { |hol| hol[:name] == "Victory Day" }
    assert_not_nil matching_holiday
    assert_equal Date.civil(2021, 8, 9), matching_holiday[:date]
    assert_includes matching_holiday[:regions], :us_ri


    assert_nil (Holidays.on(Date.civil(2017, 8, 16), [:us])[0] || {})[:name]
    assert_nil (Holidays.on(Date.civil(2020, 8, 17), [:us])[0] || {})[:name]
    assert_nil (Holidays.on(Date.civil(2025, 8, 15), [:us])[0] || {})[:name]

    holidays = Holidays.on(Date.civil(2017, 8, 16), [:us_vt], [:observed])
    matching_holiday = holidays.find { |hol| hol[:name] == "Bennington Battle Day" }
    assert_not_nil matching_holiday
    assert_equal Date.civil(2017, 8, 16), matching_holiday[:date]
    assert_includes matching_holiday[:regions], :us_vt

    holidays = Holidays.on(Date.civil(2020, 8, 17), [:us_vt], [:observed])
    matching_holiday = holidays.find { |hol| hol[:name] == "Bennington Battle Day" }
    assert_not_nil matching_holiday
    assert_equal Date.civil(2020, 8, 17), matching_holiday[:date]
    assert_includes matching_holiday[:regions], :us_vt

    holidays = Holidays.on(Date.civil(2025, 8, 15), [:us_vt], [:observed])
    matching_holiday = holidays.find { |hol| hol[:name] == "Bennington Battle Day" }
    assert_not_nil matching_holiday
    assert_equal Date.civil(2025, 8, 15), matching_holiday[:date]
    assert_includes matching_holiday[:regions], :us_vt


    holidays = Holidays.on(Date.civil(2017, 8, 16), [:us_vt])
    matching_holiday = holidays.find { |hol| hol[:name] == "Bennington Battle Day" }
    assert_not_nil matching_holiday
    assert_equal Date.civil(2017, 8, 16), matching_holiday[:date]
    assert_includes matching_holiday[:regions], :us_vt


    assert_nil (Holidays.on(Date.civil(2017, 8, 18), [:us])[0] || {})[:name]
    assert_nil (Holidays.on(Date.civil(2020, 8, 21), [:us])[0] || {})[:name]
    assert_nil (Holidays.on(Date.civil(2025, 8, 15), [:us])[0] || {})[:name]

    holidays = Holidays.on(Date.civil(2017, 8, 18), [:us_hi])
    matching_holiday = holidays.find { |hol| hol[:name] == "Statehood Day" }
    assert_not_nil matching_holiday
    assert_equal Date.civil(2017, 8, 18), matching_holiday[:date]
    assert_includes matching_holiday[:regions], :us_hi

    holidays = Holidays.on(Date.civil(2020, 8, 21), [:us_hi])
    matching_holiday = holidays.find { |hol| hol[:name] == "Statehood Day" }
    assert_not_nil matching_holiday
    assert_equal Date.civil(2020, 8, 21), matching_holiday[:date]
    assert_includes matching_holiday[:regions], :us_hi

    holidays = Holidays.on(Date.civil(2025, 8, 15), [:us_hi])
    matching_holiday = holidays.find { |hol| hol[:name] == "Statehood Day" }
    assert_not_nil matching_holiday
    assert_equal Date.civil(2025, 8, 15), matching_holiday[:date]
    assert_includes matching_holiday[:regions], :us_hi


    holidays = Holidays.on(Date.civil(2017, 8, 27), [:us_tx])
    matching_holiday = holidays.find { |hol| hol[:name] == "Lyndon Baines Johnson Day" }
    assert_not_nil matching_holiday
    assert_equal Date.civil(2017, 8, 27), matching_holiday[:date]
    assert_includes matching_holiday[:regions], :us_tx


    holidays = Holidays.on(Date.civil(2017, 9, 4), [:us])
    matching_holiday = holidays.find { |hol| hol[:name] == "Labor Day" }
    assert_not_nil matching_holiday
    assert_equal Date.civil(2017, 9, 4), matching_holiday[:date]
    assert_includes matching_holiday[:regions], :us

    holidays = Holidays.on(Date.civil(2018, 9, 3), [:us])
    matching_holiday = holidays.find { |hol| hol[:name] == "Labor Day" }
    assert_not_nil matching_holiday
    assert_equal Date.civil(2018, 9, 3), matching_holiday[:date]
    assert_includes matching_holiday[:regions], :us

    holidays = Holidays.on(Date.civil(2019, 9, 2), [:us])
    matching_holiday = holidays.find { |hol| hol[:name] == "Labor Day" }
    assert_not_nil matching_holiday
    assert_equal Date.civil(2019, 9, 2), matching_holiday[:date]
    assert_includes matching_holiday[:regions], :us


    assert_nil (Holidays.on(Date.civil(2017, 9, 21), [:us])[0] || {})[:name]
    assert_nil (Holidays.on(Date.civil(2018, 9, 10), [:us])[0] || {})[:name]
    assert_nil (Holidays.on(Date.civil(2019, 9, 30), [:us])[0] || {})[:name]

    holidays = Holidays.on(Date.civil(2017, 9, 21), [:us_tx])
    matching_holiday = holidays.find { |hol| hol[:name] == "Rosh Hashanah" }
    assert_not_nil matching_holiday
    assert_equal Date.civil(2017, 9, 21), matching_holiday[:date]
    assert_includes matching_holiday[:regions], :us_tx

    holidays = Holidays.on(Date.civil(2018, 9, 10), [:us_tx])
    matching_holiday = holidays.find { |hol| hol[:name] == "Rosh Hashanah" }
    assert_not_nil matching_holiday
    assert_equal Date.civil(2018, 9, 10), matching_holiday[:date]
    assert_includes matching_holiday[:regions], :us_tx

    holidays = Holidays.on(Date.civil(2019, 9, 30), [:us_tx])
    matching_holiday = holidays.find { |hol| hol[:name] == "Rosh Hashanah" }
    assert_not_nil matching_holiday
    assert_equal Date.civil(2019, 9, 30), matching_holiday[:date]
    assert_includes matching_holiday[:regions], :us_tx


    assert_nil (Holidays.on(Date.civil(2017, 9, 30), [:us])[0] || {})[:name]
    assert_nil (Holidays.on(Date.civil(2018, 9, 19), [:us])[0] || {})[:name]
    assert_nil (Holidays.on(Date.civil(2019, 10, 9), [:us])[0] || {})[:name]

    holidays = Holidays.on(Date.civil(2017, 9, 30), [:us_tx])
    matching_holiday = holidays.find { |hol| hol[:name] == "Yom Kippur" }
    assert_not_nil matching_holiday
    assert_equal Date.civil(2017, 9, 30), matching_holiday[:date]
    assert_includes matching_holiday[:regions], :us_tx

    holidays = Holidays.on(Date.civil(2018, 9, 19), [:us_tx])
    matching_holiday = holidays.find { |hol| hol[:name] == "Yom Kippur" }
    assert_not_nil matching_holiday
    assert_equal Date.civil(2018, 9, 19), matching_holiday[:date]
    assert_includes matching_holiday[:regions], :us_tx

    holidays = Holidays.on(Date.civil(2019, 10, 9), [:us_tx])
    matching_holiday = holidays.find { |hol| hol[:name] == "Yom Kippur" }
    assert_not_nil matching_holiday
    assert_equal Date.civil(2019, 10, 9), matching_holiday[:date]
    assert_includes matching_holiday[:regions], :us_tx


    assert_nil (Holidays.on(Date.civil(2017, 10, 9), [:us])[0] || {})[:name]
    assert_nil (Holidays.on(Date.civil(2018, 10, 8), [:us])[0] || {})[:name]
    assert_nil (Holidays.on(Date.civil(2019, 10, 14), [:us])[0] || {})[:name]

    holidays = Holidays.on(Date.civil(2017, 10, 9), [:us_al, :us_az, :us_co, :us_ct, :us_dc, :us_ga, :us_id, :us_il, :us_in, :us_ma, :us_md, :us_me, :us_mo, :us_mt, :us_ne, :us_nj, :us_nm, :us_ny, :us_oh, :us_pa, :us_ri, :us_ut, :us_va, :us_wv])
    matching_holiday = holidays.find { |hol| hol[:name] == "Columbus Day" }
    assert_not_nil matching_holiday
    assert_equal Date.civil(2017, 10, 9), matching_holiday[:date]
    assert_includes matching_holiday[:regions], :us_al
    assert_includes matching_holiday[:regions], :us_az
    assert_includes matching_holiday[:regions], :us_co
    assert_includes matching_holiday[:regions], :us_ct
    assert_includes matching_holiday[:regions], :us_dc
    assert_includes matching_holiday[:regions], :us_ga
    assert_includes matching_holiday[:regions], :us_id
    assert_includes matching_holiday[:regions], :us_il
    assert_includes matching_holiday[:regions], :us_in
    assert_includes matching_holiday[:regions], :us_ma
    assert_includes matching_holiday[:regions], :us_md
    assert_includes matching_holiday[:regions], :us_me
    assert_includes matching_holiday[:regions], :us_mo
    assert_includes matching_holiday[:regions], :us_mt
    assert_includes matching_holiday[:regions], :us_ne
    assert_includes matching_holiday[:regions], :us_nj
    assert_includes matching_holiday[:regions], :us_nm
    assert_includes matching_holiday[:regions], :us_ny
    assert_includes matching_holiday[:regions], :us_oh
    assert_includes matching_holiday[:regions], :us_pa
    assert_includes matching_holiday[:regions], :us_ri
    assert_includes matching_holiday[:regions], :us_ut
    assert_includes matching_holiday[:regions], :us_va
    assert_includes matching_holiday[:regions], :us_wv

    holidays = Holidays.on(Date.civil(2018, 10, 8), [:us_al, :us_az, :us_co, :us_ct, :us_dc, :us_ga, :us_id, :us_il, :us_in, :us_ma, :us_md, :us_me, :us_mo, :us_mt, :us_ne, :us_nj, :us_nm, :us_ny, :us_oh, :us_pa, :us_ri, :us_ut, :us_va, :us_wv])
    matching_holiday = holidays.find { |hol| hol[:name] == "Columbus Day" }
    assert_not_nil matching_holiday
    assert_equal Date.civil(2018, 10, 8), matching_holiday[:date]
    assert_includes matching_holiday[:regions], :us_al
    assert_includes matching_holiday[:regions], :us_az
    assert_includes matching_holiday[:regions], :us_co
    assert_includes matching_holiday[:regions], :us_ct
    assert_includes matching_holiday[:regions], :us_dc
    assert_includes matching_holiday[:regions], :us_ga
    assert_includes matching_holiday[:regions], :us_id
    assert_includes matching_holiday[:regions], :us_il
    assert_includes matching_holiday[:regions], :us_in
    assert_includes matching_holiday[:regions], :us_ma
    assert_includes matching_holiday[:regions], :us_md
    assert_includes matching_holiday[:regions], :us_me
    assert_includes matching_holiday[:regions], :us_mo
    assert_includes matching_holiday[:regions], :us_mt
    assert_includes matching_holiday[:regions], :us_ne
    assert_includes matching_holiday[:regions], :us_nj
    assert_includes matching_holiday[:regions], :us_nm
    assert_includes matching_holiday[:regions], :us_ny
    assert_includes matching_holiday[:regions], :us_oh
    assert_includes matching_holiday[:regions], :us_pa
    assert_includes matching_holiday[:regions], :us_ri
    assert_includes matching_holiday[:regions], :us_ut
    assert_includes matching_holiday[:regions], :us_va
    assert_includes matching_holiday[:regions], :us_wv

    holidays = Holidays.on(Date.civil(2019, 10, 14), [:us_al, :us_az, :us_co, :us_ct, :us_dc, :us_ga, :us_id, :us_il, :us_in, :us_ma, :us_md, :us_me, :us_mo, :us_mt, :us_ne, :us_nj, :us_nm, :us_ny, :us_oh, :us_pa, :us_ri, :us_ut, :us_va, :us_wv])
    matching_holiday = holidays.find { |hol| hol[:name] == "Columbus Day" }
    assert_not_nil matching_holiday
    assert_equal Date.civil(2019, 10, 14), matching_holiday[:date]
    assert_includes matching_holiday[:regions], :us_al
    assert_includes matching_holiday[:regions], :us_az
    assert_includes matching_holiday[:regions], :us_co
    assert_includes matching_holiday[:regions], :us_ct
    assert_includes matching_holiday[:regions], :us_dc
    assert_includes matching_holiday[:regions], :us_ga
    assert_includes matching_holiday[:regions], :us_id
    assert_includes matching_holiday[:regions], :us_il
    assert_includes matching_holiday[:regions], :us_in
    assert_includes matching_holiday[:regions], :us_ma
    assert_includes matching_holiday[:regions], :us_md
    assert_includes matching_holiday[:regions], :us_me
    assert_includes matching_holiday[:regions], :us_mo
    assert_includes matching_holiday[:regions], :us_mt
    assert_includes matching_holiday[:regions], :us_ne
    assert_includes matching_holiday[:regions], :us_nj
    assert_includes matching_holiday[:regions], :us_nm
    assert_includes matching_holiday[:regions], :us_ny
    assert_includes matching_holiday[:regions], :us_oh
    assert_includes matching_holiday[:regions], :us_pa
    assert_includes matching_holiday[:regions], :us_ri
    assert_includes matching_holiday[:regions], :us_ut
    assert_includes matching_holiday[:regions], :us_va
    assert_includes matching_holiday[:regions], :us_wv


    holidays = Holidays.on(Date.civil(2017, 10, 9), [:us_ak, :us_ar, :us_ca, :us_de, :us_fl, :us_hi, :us_mi, :us_mn, :us_nd, :us_nv, :us_or, :us_sd, :us_tx, :us_vt, :us_wa, :us_wi, :us_wy], [:informal])
    matching_holiday = holidays.find { |hol| hol[:name] == "Columbus Day" }
    assert_not_nil matching_holiday
    assert_equal Date.civil(2017, 10, 9), matching_holiday[:date]
    assert_includes matching_holiday[:regions], :us_ak
    assert_includes matching_holiday[:regions], :us_ar
    assert_includes matching_holiday[:regions], :us_ca
    assert_includes matching_holiday[:regions], :us_de
    assert_includes matching_holiday[:regions], :us_fl
    assert_includes matching_holiday[:regions], :us_hi
    assert_includes matching_holiday[:regions], :us_mi
    assert_includes matching_holiday[:regions], :us_mn
    assert_includes matching_holiday[:regions], :us_nd
    assert_includes matching_holiday[:regions], :us_nv
    assert_includes matching_holiday[:regions], :us_or
    assert_includes matching_holiday[:regions], :us_sd
    assert_includes matching_holiday[:regions], :us_tx
    assert_includes matching_holiday[:regions], :us_vt
    assert_includes matching_holiday[:regions], :us_wa
    assert_includes matching_holiday[:regions], :us_wi
    assert_includes matching_holiday[:regions], :us_wy

    holidays = Holidays.on(Date.civil(2018, 10, 8), [:us_ak, :us_ar, :us_ca, :us_de, :us_fl, :us_hi, :us_mi, :us_mn, :us_nd, :us_nv, :us_or, :us_sd, :us_tx, :us_vt, :us_wa, :us_wi, :us_wy], [:informal])
    matching_holiday = holidays.find { |hol| hol[:name] == "Columbus Day" }
    assert_not_nil matching_holiday
    assert_equal Date.civil(2018, 10, 8), matching_holiday[:date]
    assert_includes matching_holiday[:regions], :us_ak
    assert_includes matching_holiday[:regions], :us_ar
    assert_includes matching_holiday[:regions], :us_ca
    assert_includes matching_holiday[:regions], :us_de
    assert_includes matching_holiday[:regions], :us_fl
    assert_includes matching_holiday[:regions], :us_hi
    assert_includes matching_holiday[:regions], :us_mi
    assert_includes matching_holiday[:regions], :us_mn
    assert_includes matching_holiday[:regions], :us_nd
    assert_includes matching_holiday[:regions], :us_nv
    assert_includes matching_holiday[:regions], :us_or
    assert_includes matching_holiday[:regions], :us_sd
    assert_includes matching_holiday[:regions], :us_tx
    assert_includes matching_holiday[:regions], :us_vt
    assert_includes matching_holiday[:regions], :us_wa
    assert_includes matching_holiday[:regions], :us_wi
    assert_includes matching_holiday[:regions], :us_wy

    holidays = Holidays.on(Date.civil(2019, 10, 14), [:us_ak, :us_ar, :us_ca, :us_de, :us_fl, :us_hi, :us_mi, :us_mn, :us_nd, :us_nv, :us_or, :us_sd, :us_tx, :us_vt, :us_wa, :us_wi, :us_wy], [:informal])
    matching_holiday = holidays.find { |hol| hol[:name] == "Columbus Day" }
    assert_not_nil matching_holiday
    assert_equal Date.civil(2019, 10, 14), matching_holiday[:date]
    assert_includes matching_holiday[:regions], :us_ak
    assert_includes matching_holiday[:regions], :us_ar
    assert_includes matching_holiday[:regions], :us_ca
    assert_includes matching_holiday[:regions], :us_de
    assert_includes matching_holiday[:regions], :us_fl
    assert_includes matching_holiday[:regions], :us_hi
    assert_includes matching_holiday[:regions], :us_mi
    assert_includes matching_holiday[:regions], :us_mn
    assert_includes matching_holiday[:regions], :us_nd
    assert_includes matching_holiday[:regions], :us_nv
    assert_includes matching_holiday[:regions], :us_or
    assert_includes matching_holiday[:regions], :us_sd
    assert_includes matching_holiday[:regions], :us_tx
    assert_includes matching_holiday[:regions], :us_vt
    assert_includes matching_holiday[:regions], :us_wa
    assert_includes matching_holiday[:regions], :us_wi
    assert_includes matching_holiday[:regions], :us_wy


    assert_nil (Holidays.on(Date.civil(2017, 10, 9), [:us_ak, :us_ar, :us_ca, :us_de, :us_fl, :us_hi, :us_mi, :us_mn, :us_nd, :us_nv, :us_or, :us_sd, :us_tx, :us_vt, :us_wa, :us_wi, :us_wy])[0] || {})[:name]
    assert_nil (Holidays.on(Date.civil(2018, 10, 8), [:us_ak, :us_ar, :us_ca, :us_de, :us_fl, :us_hi, :us_mi, :us_mn, :us_nd, :us_nv, :us_or, :us_sd, :us_tx, :us_vt, :us_wa, :us_wi, :us_wy])[0] || {})[:name]
    assert_nil (Holidays.on(Date.civil(2019, 10, 14), [:us_ak, :us_ar, :us_ca, :us_de, :us_fl, :us_hi, :us_mi, :us_mn, :us_nd, :us_nv, :us_or, :us_sd, :us_tx, :us_vt, :us_wa, :us_wi, :us_wy])[0] || {})[:name]

    holidays = Holidays.on(Date.civil(2017, 10, 18), [:us_ak])
    matching_holiday = holidays.find { |hol| hol[:name] == "Alaska Day" }
    assert_not_nil matching_holiday
    assert_equal Date.civil(2017, 10, 18), matching_holiday[:date]
    assert_includes matching_holiday[:regions], :us_ak


    assert_nil (Holidays.on(Date.civil(2017, 10, 27), [:us])[0] || {})[:name]
    assert_nil (Holidays.on(Date.civil(2018, 10, 26), [:us])[0] || {})[:name]
    assert_nil (Holidays.on(Date.civil(2019, 10, 25), [:us])[0] || {})[:name]

    holidays = Holidays.on(Date.civil(2017, 10, 27), [:us_nv])
    matching_holiday = holidays.find { |hol| hol[:name] == "Nevada Day" }
    assert_not_nil matching_holiday
    assert_equal Date.civil(2017, 10, 27), matching_holiday[:date]
    assert_includes matching_holiday[:regions], :us_nv

    holidays = Holidays.on(Date.civil(2018, 10, 26), [:us_nv])
    matching_holiday = holidays.find { |hol| hol[:name] == "Nevada Day" }
    assert_not_nil matching_holiday
    assert_equal Date.civil(2018, 10, 26), matching_holiday[:date]
    assert_includes matching_holiday[:regions], :us_nv

    holidays = Holidays.on(Date.civil(2019, 10, 25), [:us_nv])
    matching_holiday = holidays.find { |hol| hol[:name] == "Nevada Day" }
    assert_not_nil matching_holiday
    assert_equal Date.civil(2019, 10, 25), matching_holiday[:date]
    assert_includes matching_holiday[:regions], :us_nv


    assert_nil (Holidays.on(Date.civil(2017, 11, 7), [:us])[0] || {})[:name]
    assert_nil (Holidays.on(Date.civil(2018, 11, 6), [:us])[0] || {})[:name]
    assert_nil (Holidays.on(Date.civil(2021, 11, 2), [:us])[0] || {})[:name]

    holidays = Holidays.on(Date.civil(2017, 11, 7), [:us_de, :us_hi, :us_in, :us_mt, :us_nj, :us_ny, :us_pa, :us_ri])
    matching_holiday = holidays.find { |hol| hol[:name] == "Election Day" }
    assert_not_nil matching_holiday
    assert_equal Date.civil(2017, 11, 7), matching_holiday[:date]
    assert_includes matching_holiday[:regions], :us_de
    assert_includes matching_holiday[:regions], :us_hi
    assert_includes matching_holiday[:regions], :us_in
    assert_includes matching_holiday[:regions], :us_mt
    assert_includes matching_holiday[:regions], :us_nj
    assert_includes matching_holiday[:regions], :us_ny
    assert_includes matching_holiday[:regions], :us_pa
    assert_includes matching_holiday[:regions], :us_ri

    holidays = Holidays.on(Date.civil(2018, 11, 6), [:us_de, :us_hi, :us_in, :us_mt, :us_nj, :us_ny, :us_pa, :us_ri])
    matching_holiday = holidays.find { |hol| hol[:name] == "Election Day" }
    assert_not_nil matching_holiday
    assert_equal Date.civil(2018, 11, 6), matching_holiday[:date]
    assert_includes matching_holiday[:regions], :us_de
    assert_includes matching_holiday[:regions], :us_hi
    assert_includes matching_holiday[:regions], :us_in
    assert_includes matching_holiday[:regions], :us_mt
    assert_includes matching_holiday[:regions], :us_nj
    assert_includes matching_holiday[:regions], :us_ny
    assert_includes matching_holiday[:regions], :us_pa
    assert_includes matching_holiday[:regions], :us_ri

    holidays = Holidays.on(Date.civil(2021, 11, 2), [:us_de, :us_hi, :us_in, :us_mt, :us_nj, :us_ny, :us_pa, :us_ri])
    matching_holiday = holidays.find { |hol| hol[:name] == "Election Day" }
    assert_not_nil matching_holiday
    assert_equal Date.civil(2021, 11, 2), matching_holiday[:date]
    assert_includes matching_holiday[:regions], :us_de
    assert_includes matching_holiday[:regions], :us_hi
    assert_includes matching_holiday[:regions], :us_in
    assert_includes matching_holiday[:regions], :us_mt
    assert_includes matching_holiday[:regions], :us_nj
    assert_includes matching_holiday[:regions], :us_ny
    assert_includes matching_holiday[:regions], :us_pa
    assert_includes matching_holiday[:regions], :us_ri


    holidays = Holidays.on(Date.civil(2017, 11, 10), [:us], [:observed])
    matching_holiday = holidays.find { |hol| hol[:name] == "Veterans Day" }
    assert_not_nil matching_holiday
    assert_equal Date.civil(2017, 11, 10), matching_holiday[:date]
    assert_includes matching_holiday[:regions], :us

    holidays = Holidays.on(Date.civil(2018, 11, 12), [:us], [:observed])
    matching_holiday = holidays.find { |hol| hol[:name] == "Veterans Day" }
    assert_not_nil matching_holiday
    assert_equal Date.civil(2018, 11, 12), matching_holiday[:date]
    assert_includes matching_holiday[:regions], :us

    holidays = Holidays.on(Date.civil(2019, 11, 11), [:us], [:observed])
    matching_holiday = holidays.find { |hol| hol[:name] == "Veterans Day" }
    assert_not_nil matching_holiday
    assert_equal Date.civil(2019, 11, 11), matching_holiday[:date]
    assert_includes matching_holiday[:regions], :us


    holidays = Holidays.on(Date.civil(2017, 11, 11), [:us])
    matching_holiday = holidays.find { |hol| hol[:name] == "Veterans Day" }
    assert_not_nil matching_holiday
    assert_equal Date.civil(2017, 11, 11), matching_holiday[:date]
    assert_includes matching_holiday[:regions], :us


    holidays = Holidays.on(Date.civil(2017, 11, 23), [:us])
    matching_holiday = holidays.find { |hol| hol[:name] == "Thanksgiving" }
    assert_not_nil matching_holiday
    assert_equal Date.civil(2017, 11, 23), matching_holiday[:date]
    assert_includes matching_holiday[:regions], :us

    holidays = Holidays.on(Date.civil(2018, 11, 22), [:us])
    matching_holiday = holidays.find { |hol| hol[:name] == "Thanksgiving" }
    assert_not_nil matching_holiday
    assert_equal Date.civil(2018, 11, 22), matching_holiday[:date]
    assert_includes matching_holiday[:regions], :us

    holidays = Holidays.on(Date.civil(2019, 11, 28), [:us])
    matching_holiday = holidays.find { |hol| hol[:name] == "Thanksgiving" }
    assert_not_nil matching_holiday
    assert_equal Date.civil(2019, 11, 28), matching_holiday[:date]
    assert_includes matching_holiday[:regions], :us


    assert_nil (Holidays.on(Date.civil(2017, 11, 24), [:us])[0] || {})[:name]
    assert_nil (Holidays.on(Date.civil(2018, 11, 23), [:us])[0] || {})[:name]
    assert_nil (Holidays.on(Date.civil(2019, 11, 29), [:us])[0] || {})[:name]

    holidays = Holidays.on(Date.civil(2017, 11, 24), [:us_nv])
    matching_holiday = holidays.find { |hol| hol[:name] == "Family Day" }
    assert_not_nil matching_holiday
    assert_equal Date.civil(2017, 11, 24), matching_holiday[:date]
    assert_includes matching_holiday[:regions], :us_nv

    holidays = Holidays.on(Date.civil(2018, 11, 23), [:us_nv])
    matching_holiday = holidays.find { |hol| hol[:name] == "Family Day" }
    assert_not_nil matching_holiday
    assert_equal Date.civil(2018, 11, 23), matching_holiday[:date]
    assert_includes matching_holiday[:regions], :us_nv

    holidays = Holidays.on(Date.civil(2019, 11, 29), [:us_nv])
    matching_holiday = holidays.find { |hol| hol[:name] == "Family Day" }
    assert_not_nil matching_holiday
    assert_equal Date.civil(2019, 11, 29), matching_holiday[:date]
    assert_includes matching_holiday[:regions], :us_nv


    holidays = Holidays.on(Date.civil(2017, 11, 24), [:us_ga])
    matching_holiday = holidays.find { |hol| hol[:name] == "State Holiday" }
    assert_not_nil matching_holiday
    assert_equal Date.civil(2017, 11, 24), matching_holiday[:date]
    assert_includes matching_holiday[:regions], :us_ga

    holidays = Holidays.on(Date.civil(2018, 11, 23), [:us_ga])
    matching_holiday = holidays.find { |hol| hol[:name] == "State Holiday" }
    assert_not_nil matching_holiday
    assert_equal Date.civil(2018, 11, 23), matching_holiday[:date]
    assert_includes matching_holiday[:regions], :us_ga

    holidays = Holidays.on(Date.civil(2019, 11, 29), [:us_ga])
    matching_holiday = holidays.find { |hol| hol[:name] == "State Holiday" }
    assert_not_nil matching_holiday
    assert_equal Date.civil(2019, 11, 29), matching_holiday[:date]
    assert_includes matching_holiday[:regions], :us_ga


    holidays = Holidays.on(Date.civil(2017, 11, 24), [:us_nm])
    matching_holiday = holidays.find { |hol| hol[:name] == "Presidents' Day" }
    assert_not_nil matching_holiday
    assert_equal Date.civil(2017, 11, 24), matching_holiday[:date]
    assert_includes matching_holiday[:regions], :us_nm

    holidays = Holidays.on(Date.civil(2018, 11, 23), [:us_nm])
    matching_holiday = holidays.find { |hol| hol[:name] == "Presidents' Day" }
    assert_not_nil matching_holiday
    assert_equal Date.civil(2018, 11, 23), matching_holiday[:date]
    assert_includes matching_holiday[:regions], :us_nm

    holidays = Holidays.on(Date.civil(2019, 11, 29), [:us_nm])
    matching_holiday = holidays.find { |hol| hol[:name] == "Presidents' Day" }
    assert_not_nil matching_holiday
    assert_equal Date.civil(2019, 11, 29), matching_holiday[:date]
    assert_includes matching_holiday[:regions], :us_nm


    holidays = Holidays.on(Date.civil(2017, 11, 24), [:us_in])
    matching_holiday = holidays.find { |hol| hol[:name] == "Lincoln's Birthday" }
    assert_not_nil matching_holiday
    assert_equal Date.civil(2017, 11, 24), matching_holiday[:date]
    assert_includes matching_holiday[:regions], :us_in

    holidays = Holidays.on(Date.civil(2018, 11, 23), [:us_in])
    matching_holiday = holidays.find { |hol| hol[:name] == "Lincoln's Birthday" }
    assert_not_nil matching_holiday
    assert_equal Date.civil(2018, 11, 23), matching_holiday[:date]
    assert_includes matching_holiday[:regions], :us_in

    holidays = Holidays.on(Date.civil(2019, 11, 29), [:us_in])
    matching_holiday = holidays.find { |hol| hol[:name] == "Lincoln's Birthday" }
    assert_not_nil matching_holiday
    assert_equal Date.civil(2019, 11, 29), matching_holiday[:date]
    assert_includes matching_holiday[:regions], :us_in


    holidays = Holidays.on(Date.civil(2017, 11, 24), [:us_md])
    matching_holiday = holidays.find { |hol| hol[:name] == "American Indian Heritage Day" }
    assert_not_nil matching_holiday
    assert_equal Date.civil(2017, 11, 24), matching_holiday[:date]
    assert_includes matching_holiday[:regions], :us_md

    holidays = Holidays.on(Date.civil(2018, 11, 23), [:us_md])
    matching_holiday = holidays.find { |hol| hol[:name] == "American Indian Heritage Day" }
    assert_not_nil matching_holiday
    assert_equal Date.civil(2018, 11, 23), matching_holiday[:date]
    assert_includes matching_holiday[:regions], :us_md

    holidays = Holidays.on(Date.civil(2019, 11, 29), [:us_md])
    matching_holiday = holidays.find { |hol| hol[:name] == "American Indian Heritage Day" }
    assert_not_nil matching_holiday
    assert_equal Date.civil(2019, 11, 29), matching_holiday[:date]
    assert_includes matching_holiday[:regions], :us_md


    holidays = Holidays.on(Date.civil(2017, 11, 24), [:us_ca, :us_de, :us_fl, :us_ia, :us_il, :us_ks, :us_ky, :us_me, :us_mi, :us_mn, :us_ms, :us_ne, :us_nh, :us_nc, :us_pa, :us_sc, :us_ok, :us_tn, :us_tx, :us_va, :us_wa, :us_wv])
    matching_holiday = holidays.find { |hol| hol[:name] == "Day after Thanksgiving (Black Friday)" }
    assert_not_nil matching_holiday
    assert_equal Date.civil(2017, 11, 24), matching_holiday[:date]
    assert_includes matching_holiday[:regions], :us_ca
    assert_includes matching_holiday[:regions], :us_de
    assert_includes matching_holiday[:regions], :us_fl
    assert_includes matching_holiday[:regions], :us_ia
    assert_includes matching_holiday[:regions], :us_il
    assert_includes matching_holiday[:regions], :us_ks
    assert_includes matching_holiday[:regions], :us_ky
    assert_includes matching_holiday[:regions], :us_me
    assert_includes matching_holiday[:regions], :us_mi
    assert_includes matching_holiday[:regions], :us_mn
    assert_includes matching_holiday[:regions], :us_ms
    assert_includes matching_holiday[:regions], :us_ne
    assert_includes matching_holiday[:regions], :us_nh
    assert_includes matching_holiday[:regions], :us_nc
    assert_includes matching_holiday[:regions], :us_pa
    assert_includes matching_holiday[:regions], :us_sc
    assert_includes matching_holiday[:regions], :us_ok
    assert_includes matching_holiday[:regions], :us_tn
    assert_includes matching_holiday[:regions], :us_tx
    assert_includes matching_holiday[:regions], :us_va
    assert_includes matching_holiday[:regions], :us_wa
    assert_includes matching_holiday[:regions], :us_wv

    holidays = Holidays.on(Date.civil(2018, 11, 23), [:us_ca, :us_de, :us_fl, :us_ia, :us_il, :us_ks, :us_ky, :us_me, :us_mi, :us_mn, :us_ms, :us_ne, :us_nh, :us_nc, :us_pa, :us_sc, :us_ok, :us_tn, :us_tx, :us_va, :us_wa, :us_wv])
    matching_holiday = holidays.find { |hol| hol[:name] == "Day after Thanksgiving (Black Friday)" }
    assert_not_nil matching_holiday
    assert_equal Date.civil(2018, 11, 23), matching_holiday[:date]
    assert_includes matching_holiday[:regions], :us_ca
    assert_includes matching_holiday[:regions], :us_de
    assert_includes matching_holiday[:regions], :us_fl
    assert_includes matching_holiday[:regions], :us_ia
    assert_includes matching_holiday[:regions], :us_il
    assert_includes matching_holiday[:regions], :us_ks
    assert_includes matching_holiday[:regions], :us_ky
    assert_includes matching_holiday[:regions], :us_me
    assert_includes matching_holiday[:regions], :us_mi
    assert_includes matching_holiday[:regions], :us_mn
    assert_includes matching_holiday[:regions], :us_ms
    assert_includes matching_holiday[:regions], :us_ne
    assert_includes matching_holiday[:regions], :us_nh
    assert_includes matching_holiday[:regions], :us_nc
    assert_includes matching_holiday[:regions], :us_pa
    assert_includes matching_holiday[:regions], :us_sc
    assert_includes matching_holiday[:regions], :us_ok
    assert_includes matching_holiday[:regions], :us_tn
    assert_includes matching_holiday[:regions], :us_tx
    assert_includes matching_holiday[:regions], :us_va
    assert_includes matching_holiday[:regions], :us_wa
    assert_includes matching_holiday[:regions], :us_wv

    holidays = Holidays.on(Date.civil(2019, 11, 29), [:us_ca, :us_de, :us_fl, :us_ia, :us_il, :us_ks, :us_ky, :us_me, :us_mi, :us_mn, :us_ms, :us_ne, :us_nh, :us_nc, :us_pa, :us_sc, :us_ok, :us_tn, :us_tx, :us_va, :us_wa, :us_wv])
    matching_holiday = holidays.find { |hol| hol[:name] == "Day after Thanksgiving (Black Friday)" }
    assert_not_nil matching_holiday
    assert_equal Date.civil(2019, 11, 29), matching_holiday[:date]
    assert_includes matching_holiday[:regions], :us_ca
    assert_includes matching_holiday[:regions], :us_de
    assert_includes matching_holiday[:regions], :us_fl
    assert_includes matching_holiday[:regions], :us_ia
    assert_includes matching_holiday[:regions], :us_il
    assert_includes matching_holiday[:regions], :us_ks
    assert_includes matching_holiday[:regions], :us_ky
    assert_includes matching_holiday[:regions], :us_me
    assert_includes matching_holiday[:regions], :us_mi
    assert_includes matching_holiday[:regions], :us_mn
    assert_includes matching_holiday[:regions], :us_ms
    assert_includes matching_holiday[:regions], :us_ne
    assert_includes matching_holiday[:regions], :us_nh
    assert_includes matching_holiday[:regions], :us_nc
    assert_includes matching_holiday[:regions], :us_pa
    assert_includes matching_holiday[:regions], :us_sc
    assert_includes matching_holiday[:regions], :us_ok
    assert_includes matching_holiday[:regions], :us_tn
    assert_includes matching_holiday[:regions], :us_tx
    assert_includes matching_holiday[:regions], :us_va
    assert_includes matching_holiday[:regions], :us_wa
    assert_includes matching_holiday[:regions], :us_wv


    holidays = Holidays.on(Date.civil(2022, 12, 23), [:us_mi, :us_sc, :us_va])
    matching_holiday = holidays.find { |hol| hol[:name] == "Christmas Eve (Holiday)" }
    assert_not_nil matching_holiday
    assert_equal Date.civil(2022, 12, 23), matching_holiday[:date]
    assert_includes matching_holiday[:regions], :us_mi
    assert_includes matching_holiday[:regions], :us_sc
    assert_includes matching_holiday[:regions], :us_va

    holidays = Holidays.on(Date.civil(2023, 12, 22), [:us_mi, :us_sc, :us_va])
    matching_holiday = holidays.find { |hol| hol[:name] == "Christmas Eve (Holiday)" }
    assert_not_nil matching_holiday
    assert_equal Date.civil(2023, 12, 22), matching_holiday[:date]
    assert_includes matching_holiday[:regions], :us_mi
    assert_includes matching_holiday[:regions], :us_sc
    assert_includes matching_holiday[:regions], :us_va

    holidays = Holidays.on(Date.civil(2028, 12, 22), [:us_mi, :us_sc, :us_va])
    matching_holiday = holidays.find { |hol| hol[:name] == "Christmas Eve (Holiday)" }
    assert_not_nil matching_holiday
    assert_equal Date.civil(2028, 12, 22), matching_holiday[:date]
    assert_includes matching_holiday[:regions], :us_mi
    assert_includes matching_holiday[:regions], :us_sc
    assert_includes matching_holiday[:regions], :us_va


    holidays = Holidays.on(Date.civil(2017, 12, 24), [:us_ar, :us_mi, :us_nc, :us_va, :us_sc, :us_tx, :us_wi])
    matching_holiday = holidays.find { |hol| hol[:name] == "Christmas Eve" }
    assert_not_nil matching_holiday
    assert_equal Date.civil(2017, 12, 24), matching_holiday[:date]
    assert_includes matching_holiday[:regions], :us_ar
    assert_includes matching_holiday[:regions], :us_mi
    assert_includes matching_holiday[:regions], :us_nc
    assert_includes matching_holiday[:regions], :us_va
    assert_includes matching_holiday[:regions], :us_sc
    assert_includes matching_holiday[:regions], :us_tx
    assert_includes matching_holiday[:regions], :us_wi


    assert_nil (Holidays.on(Date.civil(2021, 12, 27), [:us])[0] || {})[:name]
    assert_nil (Holidays.on(Date.civil(2022, 12, 23), [:us])[0] || {})[:name]
    assert_nil (Holidays.on(Date.civil(2027, 12, 27), [:us])[0] || {})[:name]

    holidays = Holidays.on(Date.civil(2021, 12, 24), [:us], [:observed])
    matching_holiday = holidays.find { |hol| hol[:name] == "Christmas Day" }
    assert_not_nil matching_holiday
    assert_equal Date.civil(2021, 12, 24), matching_holiday[:date]
    assert_includes matching_holiday[:regions], :us

    holidays = Holidays.on(Date.civil(2022, 12, 26), [:us], [:observed])
    matching_holiday = holidays.find { |hol| hol[:name] == "Christmas Day" }
    assert_not_nil matching_holiday
    assert_equal Date.civil(2022, 12, 26), matching_holiday[:date]
    assert_includes matching_holiday[:regions], :us

    holidays = Holidays.on(Date.civil(2027, 12, 24), [:us], [:observed])
    matching_holiday = holidays.find { |hol| hol[:name] == "Christmas Day" }
    assert_not_nil matching_holiday
    assert_equal Date.civil(2027, 12, 24), matching_holiday[:date]
    assert_includes matching_holiday[:regions], :us


    holidays = Holidays.on(Date.civil(2017, 12, 25), [:us])
    matching_holiday = holidays.find { |hol| hol[:name] == "Christmas Day" }
    assert_not_nil matching_holiday
    assert_equal Date.civil(2017, 12, 25), matching_holiday[:date]
    assert_includes matching_holiday[:regions], :us


    holidays = Holidays.on(Date.civil(2017, 12, 26), [:us_ar, :us_nc, :us_ok, :us_sc, :us_tn, :us_tx])
    matching_holiday = holidays.find { |hol| hol[:name] == "Day after Christmas" }
    assert_not_nil matching_holiday
    assert_equal Date.civil(2017, 12, 26), matching_holiday[:date]
    assert_includes matching_holiday[:regions], :us_ar
    assert_includes matching_holiday[:regions], :us_nc
    assert_includes matching_holiday[:regions], :us_ok
    assert_includes matching_holiday[:regions], :us_sc
    assert_includes matching_holiday[:regions], :us_tn
    assert_includes matching_holiday[:regions], :us_tx


    holidays = Holidays.on(Date.civil(2017, 12, 31), [:us_mi, :us_wi])
    matching_holiday = holidays.find { |hol| hol[:name] == "New Year's Eve" }
    assert_not_nil matching_holiday
    assert_equal Date.civil(2017, 12, 31), matching_holiday[:date]
    assert_includes matching_holiday[:regions], :us_mi
    assert_includes matching_holiday[:regions], :us_wi


    holidays = Holidays.on(Date.civil(2013, 2, 2), [:us], [:informal])
    matching_holiday = holidays.find { |hol| hol[:name] == "Groundhog Day" }
    assert_not_nil matching_holiday
    assert_equal Date.civil(2013, 2, 2), matching_holiday[:date]
    assert_includes matching_holiday[:regions], :us


    holidays = Holidays.on(Date.civil(2013, 2, 14), [:us], [:informal])
    matching_holiday = holidays.find { |hol| hol[:name] == "Valentine's Day" }
    assert_not_nil matching_holiday
    assert_equal Date.civil(2013, 2, 14), matching_holiday[:date]
    assert_includes matching_holiday[:regions], :us


    holidays = Holidays.on(Date.civil(2013, 3, 17), [:us], [:informal])
    matching_holiday = holidays.find { |hol| hol[:name] == "St. Patrick's Day" }
    assert_not_nil matching_holiday
    assert_equal Date.civil(2013, 3, 17), matching_holiday[:date]
    assert_includes matching_holiday[:regions], :us


    holidays = Holidays.on(Date.civil(2013, 4, 1), [:us], [:informal])
    matching_holiday = holidays.find { |hol| hol[:name] == "April Fool's Day" }
    assert_not_nil matching_holiday
    assert_equal Date.civil(2013, 4, 1), matching_holiday[:date]
    assert_includes matching_holiday[:regions], :us


    holidays = Holidays.on(Date.civil(2013, 4, 22), [:us], [:informal])
    matching_holiday = holidays.find { |hol| hol[:name] == "Earth Day" }
    assert_not_nil matching_holiday
    assert_equal Date.civil(2013, 4, 22), matching_holiday[:date]
    assert_includes matching_holiday[:regions], :us


    holidays = Holidays.on(Date.civil(2013, 5, 12), [:us], [:informal])
    matching_holiday = holidays.find { |hol| hol[:name] == "Mother's Day" }
    assert_not_nil matching_holiday
    assert_equal Date.civil(2013, 5, 12), matching_holiday[:date]
    assert_includes matching_holiday[:regions], :us


    holidays = Holidays.on(Date.civil(2013, 5, 18), [:us], [:informal])
    matching_holiday = holidays.find { |hol| hol[:name] == "Armed Forces Day" }
    assert_not_nil matching_holiday
    assert_equal Date.civil(2013, 5, 18), matching_holiday[:date]
    assert_includes matching_holiday[:regions], :us


    holidays = Holidays.on(Date.civil(2013, 6, 16), [:us], [:informal])
    matching_holiday = holidays.find { |hol| hol[:name] == "Father's Day" }
    assert_not_nil matching_holiday
    assert_equal Date.civil(2013, 6, 16), matching_holiday[:date]
    assert_includes matching_holiday[:regions], :us


    holidays = Holidays.on(Date.civil(2013, 10, 31), [:us], [:informal])
    matching_holiday = holidays.find { |hol| hol[:name] == "Halloween" }
    assert_not_nil matching_holiday
    assert_equal Date.civil(2013, 10, 31), matching_holiday[:date]
    assert_includes matching_holiday[:regions], :us


  end
end
