# encoding: utf-8
require File.expand_path(File.dirname(__FILE__)) + '/../test_helper'

# This file is generated by the Ruby Holiday gem.
#
# Definitions loaded: definitions/lu.yaml
class LuDefinitionTests < Test::Unit::TestCase  # :nodoc:

  def test_lu
    holidays = Holidays.on(Date.civil(2008, 1, 1), [:lu], [:informal])
    matching_holiday = holidays.find { |hol| hol[:name] == "Neijoerschdag" }
    assert_not_nil matching_holiday
    assert_equal Date.civil(2008, 1, 1), matching_holiday[:date]
    assert_includes matching_holiday[:regions], :lu


    holidays = Holidays.on(Date.civil(2008, 3, 24), [:lu], [:informal])
    matching_holiday = holidays.find { |hol| hol[:name] == "Ouschterméindeg" }
    assert_not_nil matching_holiday
    assert_equal Date.civil(2008, 3, 24), matching_holiday[:date]
    assert_includes matching_holiday[:regions], :lu


    holidays = Holidays.on(Date.civil(2008, 5, 1), [:lu], [:informal])
    matching_holiday = holidays.find { |hol| hol[:name] == "Christi Himmelfaart" }
    assert_not_nil matching_holiday
    assert_equal Date.civil(2008, 5, 1), matching_holiday[:date]
    assert_includes matching_holiday[:regions], :lu


    holidays = Holidays.on(Date.civil(2008, 6, 23), [:lu], [:informal])
    matching_holiday = holidays.find { |hol| hol[:name] == "Nationalfeierdag" }
    assert_not_nil matching_holiday
    assert_equal Date.civil(2008, 6, 23), matching_holiday[:date]
    assert_includes matching_holiday[:regions], :lu


    holidays = Holidays.on(Date.civil(2008, 8, 15), [:lu], [:informal])
    matching_holiday = holidays.find { |hol| hol[:name] == "Léiffrawëschdag" }
    assert_not_nil matching_holiday
    assert_equal Date.civil(2008, 8, 15), matching_holiday[:date]
    assert_includes matching_holiday[:regions], :lu


    holidays = Holidays.on(Date.civil(2008, 11, 1), [:lu], [:informal])
    matching_holiday = holidays.find { |hol| hol[:name] == "Allerhellgen" }
    assert_not_nil matching_holiday
    assert_equal Date.civil(2008, 11, 1), matching_holiday[:date]
    assert_includes matching_holiday[:regions], :lu


    holidays = Holidays.on(Date.civil(2008, 12, 25), [:lu], [:informal])
    matching_holiday = holidays.find { |hol| hol[:name] == "Chrëschtdag" }
    assert_not_nil matching_holiday
    assert_equal Date.civil(2008, 12, 25), matching_holiday[:date]
    assert_includes matching_holiday[:regions], :lu


    holidays = Holidays.on(Date.civil(2008, 12, 26), [:lu], [:informal])
    matching_holiday = holidays.find { |hol| hol[:name] == "Stiefesdag" }
    assert_not_nil matching_holiday
    assert_equal Date.civil(2008, 12, 26), matching_holiday[:date]
    assert_includes matching_holiday[:regions], :lu


    holidays = Holidays.on(Date.civil(2008, 5, 11), [:lu], [:informal])
    matching_holiday = holidays.find { |hol| hol[:name] == "Péngschtméindeg" }
    assert_not_nil matching_holiday
    assert_equal Date.civil(2008, 5, 11), matching_holiday[:date]
    assert_includes matching_holiday[:regions], :lu


  end
end
