# encoding: utf-8
require File.expand_path(File.dirname(__FILE__)) + '/../test_helper'

# This file is generated by the Ruby Holiday gem.
#
# Definitions loaded: definitions/do.yaml
class DoDefinitionTests < Test::Unit::TestCase  # :nodoc:

  def test_do
    holidays = Holidays.on(Date.civil(2026, 1, 1), [:do])
    matching_holiday = holidays.find { |hol| hol[:name] == "Año Nuevo" }
    assert_not_nil matching_holiday
    assert_equal Date.civil(2026, 1, 1), matching_holiday[:date]
    assert_includes matching_holiday[:regions], :do


    holidays = Holidays.on(Date.civil(2026, 1, 5), [:do])
    matching_holiday = holidays.find { |hol| hol[:name] == "Epifanía" }
    assert_not_nil matching_holiday
    assert_equal Date.civil(2026, 1, 5), matching_holiday[:date]
    assert_includes matching_holiday[:regions], :do


    holidays = Holidays.on(Date.civil(2026, 1, 21), [:do])
    matching_holiday = holidays.find { |hol| hol[:name] == "Día de la Altagracia" }
    assert_not_nil matching_holiday
    assert_equal Date.civil(2026, 1, 21), matching_holiday[:date]
    assert_includes matching_holiday[:regions], :do


    holidays = Holidays.on(Date.civil(2026, 1, 26), [:do])
    matching_holiday = holidays.find { |hol| hol[:name] == "Juan Pablo Duarte" }
    assert_not_nil matching_holiday
    assert_equal Date.civil(2026, 1, 26), matching_holiday[:date]
    assert_includes matching_holiday[:regions], :do


    holidays = Holidays.on(Date.civil(2026, 2, 27), [:do])
    matching_holiday = holidays.find { |hol| hol[:name] == "Día de la Independencia" }
    assert_not_nil matching_holiday
    assert_equal Date.civil(2026, 2, 27), matching_holiday[:date]
    assert_includes matching_holiday[:regions], :do


    holidays = Holidays.on(Date.civil(2026, 4, 3), [:do])
    matching_holiday = holidays.find { |hol| hol[:name] == "Viernes Santo" }
    assert_not_nil matching_holiday
    assert_equal Date.civil(2026, 4, 3), matching_holiday[:date]
    assert_includes matching_holiday[:regions], :do


    holidays = Holidays.on(Date.civil(2026, 4, 5), [:do])
    matching_holiday = holidays.find { |hol| hol[:name] == "Dia de Pascua" }
    assert_not_nil matching_holiday
    assert_equal Date.civil(2026, 4, 5), matching_holiday[:date]
    assert_includes matching_holiday[:regions], :do


    holidays = Holidays.on(Date.civil(2026, 5, 4), [:do])
    matching_holiday = holidays.find { |hol| hol[:name] == "Dia del Trabajo" }
    assert_not_nil matching_holiday
    assert_equal Date.civil(2026, 5, 4), matching_holiday[:date]
    assert_includes matching_holiday[:regions], :do


    holidays = Holidays.on(Date.civil(2026, 6, 4), [:do])
    matching_holiday = holidays.find { |hol| hol[:name] == "Corpus Christi" }
    assert_not_nil matching_holiday
    assert_equal Date.civil(2026, 6, 4), matching_holiday[:date]
    assert_includes matching_holiday[:regions], :do


    holidays = Holidays.on(Date.civil(2026, 8, 16), [:do])
    matching_holiday = holidays.find { |hol| hol[:name] == "Día de la Restauración" }
    assert_not_nil matching_holiday
    assert_equal Date.civil(2026, 8, 16), matching_holiday[:date]
    assert_includes matching_holiday[:regions], :do


    holidays = Holidays.on(Date.civil(2026, 9, 24), [:do])
    matching_holiday = holidays.find { |hol| hol[:name] == "Día de Nuestra Señora de Mercedes" }
    assert_not_nil matching_holiday
    assert_equal Date.civil(2026, 9, 24), matching_holiday[:date]
    assert_includes matching_holiday[:regions], :do


    holidays = Holidays.on(Date.civil(2026, 11, 9), [:do])
    matching_holiday = holidays.find { |hol| hol[:name] == "Día de la Constitución" }
    assert_not_nil matching_holiday
    assert_equal Date.civil(2026, 11, 9), matching_holiday[:date]
    assert_includes matching_holiday[:regions], :do


    holidays = Holidays.on(Date.civil(2026, 12, 25), [:do])
    matching_holiday = holidays.find { |hol| hol[:name] == "Navidad" }
    assert_not_nil matching_holiday
    assert_equal Date.civil(2026, 12, 25), matching_holiday[:date]
    assert_includes matching_holiday[:regions], :do


  end
end
