# encoding: utf-8
require File.expand_path(File.dirname(__FILE__)) + '/../test_helper'

# This file is generated by the Ruby Holiday gem.
#
# Definitions loaded: definitions/ecb_target.yaml
class Ecb_targetDefinitionTests < Test::Unit::TestCase  # :nodoc:

  def test_ecb_target
    holidays = Holidays.on(Date.civil(2013, 1, 1), [:ecb_target])
    matching_holiday = holidays.find { |hol| hol[:name] == "New Year's Day" }
    assert_not_nil matching_holiday
    assert_equal Date.civil(2013, 1, 1), matching_holiday[:date]
    assert_includes matching_holiday[:regions], :ecb_target


    holidays = Holidays.on(Date.civil(2013, 5, 1), [:ecb_target])
    matching_holiday = holidays.find { |hol| hol[:name] == "Labour Day" }
    assert_not_nil matching_holiday
    assert_equal Date.civil(2013, 5, 1), matching_holiday[:date]
    assert_includes matching_holiday[:regions], :ecb_target


    holidays = Holidays.on(Date.civil(2013, 3, 29), [:ecb_target])
    matching_holiday = holidays.find { |hol| hol[:name] == "Good Friday" }
    assert_not_nil matching_holiday
    assert_equal Date.civil(2013, 3, 29), matching_holiday[:date]
    assert_includes matching_holiday[:regions], :ecb_target


    holidays = Holidays.on(Date.civil(2013, 4, 1), [:ecb_target])
    matching_holiday = holidays.find { |hol| hol[:name] == "Easter Monday" }
    assert_not_nil matching_holiday
    assert_equal Date.civil(2013, 4, 1), matching_holiday[:date]
    assert_includes matching_holiday[:regions], :ecb_target


    holidays = Holidays.on(Date.civil(2013, 12, 25), [:ecb_target])
    matching_holiday = holidays.find { |hol| hol[:name] == "Christmas Day" }
    assert_not_nil matching_holiday
    assert_equal Date.civil(2013, 12, 25), matching_holiday[:date]
    assert_includes matching_holiday[:regions], :ecb_target


    holidays = Holidays.on(Date.civil(2013, 12, 26), [:ecb_target])
    matching_holiday = holidays.find { |hol| hol[:name] == "Christmas Holiday" }
    assert_not_nil matching_holiday
    assert_equal Date.civil(2013, 12, 26), matching_holiday[:date]
    assert_includes matching_holiday[:regions], :ecb_target


    holidays = Holidays.on(Date.civil(2013, 3, 29), [:ecb_target])
    matching_holiday = holidays.find { |hol| hol[:name] == "Good Friday" }
    assert_not_nil matching_holiday
    assert_equal Date.civil(2013, 3, 29), matching_holiday[:date]
    assert_includes matching_holiday[:regions], :ecb_target


    holidays = Holidays.on(Date.civil(2013, 4, 1), [:ecb_target])
    matching_holiday = holidays.find { |hol| hol[:name] == "Easter Monday" }
    assert_not_nil matching_holiday
    assert_equal Date.civil(2013, 4, 1), matching_holiday[:date]
    assert_includes matching_holiday[:regions], :ecb_target


  end
end
