# encoding: utf-8
require File.expand_path(File.dirname(__FILE__)) + '/../test_helper'

# This file is generated by the Ruby Holiday gem.
#
# Definitions loaded: definitions/el.yaml
class ElDefinitionTests < Test::Unit::TestCase  # :nodoc:

  def test_el
    holidays = Holidays.on(Date.civil(2023, 6, 4), [:el], [:informal])
    matching_holiday = holidays.find { |hol| hol[:name] == "Πεντηκοστή" }
    assert_not_nil matching_holiday
    assert_equal Date.civil(2023, 6, 4), matching_holiday[:date]
    assert_includes matching_holiday[:regions], :el


    holidays = Holidays.on(Date.civil(2024, 6, 23), [:el], [:informal])
    matching_holiday = holidays.find { |hol| hol[:name] == "Πεντηκοστή" }
    assert_not_nil matching_holiday
    assert_equal Date.civil(2024, 6, 23), matching_holiday[:date]
    assert_includes matching_holiday[:regions], :el


    holidays = Holidays.on(Date.civil(2011, 1, 1), [:el], [:informal])
    matching_holiday = holidays.find { |hol| hol[:name] == "Πρωτοχρονιά" }
    assert_not_nil matching_holiday
    assert_equal Date.civil(2011, 1, 1), matching_holiday[:date]
    assert_includes matching_holiday[:regions], :el


    holidays = Holidays.on(Date.civil(2011, 1, 6), [:el], [:informal])
    matching_holiday = holidays.find { |hol| hol[:name] == "Θεοφάνεια" }
    assert_not_nil matching_holiday
    assert_equal Date.civil(2011, 1, 6), matching_holiday[:date]
    assert_includes matching_holiday[:regions], :el


    holidays = Holidays.on(Date.civil(2011, 4, 22), [:el], [:informal])
    matching_holiday = holidays.find { |hol| hol[:name] == "Μεγάλη Παρασκευή" }
    assert_not_nil matching_holiday
    assert_equal Date.civil(2011, 4, 22), matching_holiday[:date]
    assert_includes matching_holiday[:regions], :el


    holidays = Holidays.on(Date.civil(1970, 4, 25), [:el], [:informal])
    matching_holiday = holidays.find { |hol| hol[:name] == "Μεγάλο Σάββατο" }
    assert_not_nil matching_holiday
    assert_equal Date.civil(1970, 4, 25), matching_holiday[:date]
    assert_includes matching_holiday[:regions], :el


    holidays = Holidays.on(Date.civil(1985, 4, 14), [:el], [:informal])
    matching_holiday = holidays.find { |hol| hol[:name] == "Κυριακή του Πάσχα" }
    assert_not_nil matching_holiday
    assert_equal Date.civil(1985, 4, 14), matching_holiday[:date]
    assert_includes matching_holiday[:regions], :el


    holidays = Holidays.on(Date.civil(2011, 4, 24), [:el], [:informal])
    matching_holiday = holidays.find { |hol| hol[:name] == "Κυριακή του Πάσχα" }
    assert_not_nil matching_holiday
    assert_equal Date.civil(2011, 4, 24), matching_holiday[:date]
    assert_includes matching_holiday[:regions], :el


    holidays = Holidays.on(Date.civil(2027, 5, 2), [:el], [:informal])
    matching_holiday = holidays.find { |hol| hol[:name] == "Κυριακή του Πάσχα" }
    assert_not_nil matching_holiday
    assert_equal Date.civil(2027, 5, 2), matching_holiday[:date]
    assert_includes matching_holiday[:regions], :el


    holidays = Holidays.on(Date.civil(2046, 4, 30), [:el], [:informal])
    matching_holiday = holidays.find { |hol| hol[:name] == "Δευτέρα του Πάσχα" }
    assert_not_nil matching_holiday
    assert_equal Date.civil(2046, 4, 30), matching_holiday[:date]
    assert_includes matching_holiday[:regions], :el


    holidays = Holidays.on(Date.civil(2011, 5, 1), [:el], [:informal])
    matching_holiday = holidays.find { |hol| hol[:name] == "Πρωτομαγιά" }
    assert_not_nil matching_holiday
    assert_equal Date.civil(2011, 5, 1), matching_holiday[:date]
    assert_includes matching_holiday[:regions], :el


    holidays = Holidays.on(Date.civil(2011, 6, 13), [:el], [:informal])
    matching_holiday = holidays.find { |hol| hol[:name] == "Αγίου Πνεύματος" }
    assert_not_nil matching_holiday
    assert_equal Date.civil(2011, 6, 13), matching_holiday[:date]
    assert_includes matching_holiday[:regions], :el


    holidays = Holidays.on(Date.civil(2012, 6, 4), [:el], [:informal])
    matching_holiday = holidays.find { |hol| hol[:name] == "Αγίου Πνεύματος" }
    assert_not_nil matching_holiday
    assert_equal Date.civil(2012, 6, 4), matching_holiday[:date]
    assert_includes matching_holiday[:regions], :el


    holidays = Holidays.on(Date.civil(2011, 3, 7), [:el], [:informal])
    matching_holiday = holidays.find { |hol| hol[:name] == "Καθαρά Δευτέρα" }
    assert_not_nil matching_holiday
    assert_equal Date.civil(2011, 3, 7), matching_holiday[:date]
    assert_includes matching_holiday[:regions], :el


    holidays = Holidays.on(Date.civil(2012, 2, 27), [:el], [:informal])
    matching_holiday = holidays.find { |hol| hol[:name] == "Καθαρά Δευτέρα" }
    assert_not_nil matching_holiday
    assert_equal Date.civil(2012, 2, 27), matching_holiday[:date]
    assert_includes matching_holiday[:regions], :el


    holidays = Holidays.on(Date.civil(2011, 12, 25), [:el], [:informal])
    matching_holiday = holidays.find { |hol| hol[:name] == "Χριστούγεννα" }
    assert_not_nil matching_holiday
    assert_equal Date.civil(2011, 12, 25), matching_holiday[:date]
    assert_includes matching_holiday[:regions], :el


    holidays = Holidays.on(Date.civil(2011, 12, 26), [:el], [:informal])
    matching_holiday = holidays.find { |hol| hol[:name] == "Δεύτερη ημέρα των Χριστουγέννων" }
    assert_not_nil matching_holiday
    assert_equal Date.civil(2011, 12, 26), matching_holiday[:date]
    assert_includes matching_holiday[:regions], :el


  end
end
