# encoding: utf-8
require File.expand_path(File.dirname(__FILE__)) + '/../test_helper'

# This file is generated by the Ruby Holiday gem.
#
# Definitions loaded: definitions/fedex.yaml
class FedexDefinitionTests < Test::Unit::TestCase  # :nodoc:

  def test_fedex
    holidays = Holidays.on(Date.civil(2015, 1, 1), [:ups])
    matching_holiday = holidays.find { |hol| hol[:name] == "New Year's Day" }
    assert_not_nil matching_holiday
    assert_equal Date.civil(2015, 1, 1), matching_holiday[:date]
    assert_includes matching_holiday[:regions], :ups


    holidays = Holidays.on(Date.civil(2015, 5, 25), [:ups])
    matching_holiday = holidays.find { |hol| hol[:name] == "Memorial Day" }
    assert_not_nil matching_holiday
    assert_equal Date.civil(2015, 5, 25), matching_holiday[:date]
    assert_includes matching_holiday[:regions], :ups


    holidays = Holidays.on(Date.civil(2015, 7, 4), [:ups])
    matching_holiday = holidays.find { |hol| hol[:name] == "Independence Day" }
    assert_not_nil matching_holiday
    assert_equal Date.civil(2015, 7, 4), matching_holiday[:date]
    assert_includes matching_holiday[:regions], :ups


    holidays = Holidays.on(Date.civil(2015, 9, 7), [:ups])
    matching_holiday = holidays.find { |hol| hol[:name] == "Labor Day" }
    assert_not_nil matching_holiday
    assert_equal Date.civil(2015, 9, 7), matching_holiday[:date]
    assert_includes matching_holiday[:regions], :ups


    holidays = Holidays.on(Date.civil(2015, 11, 26), [:ups])
    matching_holiday = holidays.find { |hol| hol[:name] == "Thanksgiving" }
    assert_not_nil matching_holiday
    assert_equal Date.civil(2015, 11, 26), matching_holiday[:date]
    assert_includes matching_holiday[:regions], :ups


    holidays = Holidays.on(Date.civil(2015, 11, 27), [:ups])
    matching_holiday = holidays.find { |hol| hol[:name] == "Day After Thanksgiving" }
    assert_not_nil matching_holiday
    assert_equal Date.civil(2015, 11, 27), matching_holiday[:date]
    assert_includes matching_holiday[:regions], :ups


    holidays = Holidays.on(Date.civil(2013, 11, 28), [:ups])
    matching_holiday = holidays.find { |hol| hol[:name] == "Thanksgiving" }
    assert_not_nil matching_holiday
    assert_equal Date.civil(2013, 11, 28), matching_holiday[:date]
    assert_includes matching_holiday[:regions], :ups


    holidays = Holidays.on(Date.civil(2013, 11, 29), [:ups])
    matching_holiday = holidays.find { |hol| hol[:name] == "Day After Thanksgiving" }
    assert_not_nil matching_holiday
    assert_equal Date.civil(2013, 11, 29), matching_holiday[:date]
    assert_includes matching_holiday[:regions], :ups


    holidays = Holidays.on(Date.civil(2015, 12, 25), [:ups])
    matching_holiday = holidays.find { |hol| hol[:name] == "Christmas Day" }
    assert_not_nil matching_holiday
    assert_equal Date.civil(2015, 12, 25), matching_holiday[:date]
    assert_includes matching_holiday[:regions], :ups


    holidays = Holidays.on(Date.civil(2015, 12, 31), [:ups])
    matching_holiday = holidays.find { |hol| hol[:name] == "New Year's Eve" }
    assert_not_nil matching_holiday
    assert_equal Date.civil(2015, 12, 31), matching_holiday[:date]
    assert_includes matching_holiday[:regions], :ups


  end
end
