# encoding: utf-8
require File.expand_path(File.dirname(__FILE__)) + '/../test_helper'

# This file is generated by the Ruby Holiday gem.
#
# Definitions loaded: definitions/ph.yaml
class PhDefinitionTests < Test::Unit::TestCase  # :nodoc:

  def test_ph
    holidays = Holidays.on(Date.civil(2015, 4, 3), [:ph])
    matching_holiday = holidays.find { |hol| hol[:name] == "Good Friday" }
    assert_not_nil matching_holiday
    assert_equal Date.civil(2015, 4, 3), matching_holiday[:date]
    assert_includes matching_holiday[:regions], :ph


    holidays = Holidays.on(Date.civil(2015, 4, 9), [:ph])
    matching_holiday = holidays.find { |hol| hol[:name] == "The Day of Valor" }
    assert_not_nil matching_holiday
    assert_equal Date.civil(2015, 4, 9), matching_holiday[:date]
    assert_includes matching_holiday[:regions], :ph


    holidays = Holidays.on(Date.civil(2015, 5, 1), [:ph])
    matching_holiday = holidays.find { |hol| hol[:name] == "Labor Day" }
    assert_not_nil matching_holiday
    assert_equal Date.civil(2015, 5, 1), matching_holiday[:date]
    assert_includes matching_holiday[:regions], :ph


    holidays = Holidays.on(Date.civil(2015, 6, 12), [:ph])
    matching_holiday = holidays.find { |hol| hol[:name] == "Independence Day" }
    assert_not_nil matching_holiday
    assert_equal Date.civil(2015, 6, 12), matching_holiday[:date]
    assert_includes matching_holiday[:regions], :ph


    holidays = Holidays.on(Date.civil(2015, 8, 21), [:ph])
    matching_holiday = holidays.find { |hol| hol[:name] == "Ninoy Aquino Day" }
    assert_not_nil matching_holiday
    assert_equal Date.civil(2015, 8, 21), matching_holiday[:date]
    assert_includes matching_holiday[:regions], :ph


    holidays = Holidays.on(Date.civil(2015, 8, 31), [:ph])
    matching_holiday = holidays.find { |hol| hol[:name] == "National Heroes Day" }
    assert_not_nil matching_holiday
    assert_equal Date.civil(2015, 8, 31), matching_holiday[:date]
    assert_includes matching_holiday[:regions], :ph


    holidays = Holidays.on(Date.civil(2015, 11, 30), [:ph])
    matching_holiday = holidays.find { |hol| hol[:name] == "Bonifacio Day" }
    assert_not_nil matching_holiday
    assert_equal Date.civil(2015, 11, 30), matching_holiday[:date]
    assert_includes matching_holiday[:regions], :ph


    holidays = Holidays.on(Date.civil(2015, 12, 25), [:ph])
    matching_holiday = holidays.find { |hol| hol[:name] == "Christmas Day" }
    assert_not_nil matching_holiday
    assert_equal Date.civil(2015, 12, 25), matching_holiday[:date]
    assert_includes matching_holiday[:regions], :ph


    holidays = Holidays.on(Date.civil(2015, 12, 30), [:ph])
    matching_holiday = holidays.find { |hol| hol[:name] == "Rizal Day" }
    assert_not_nil matching_holiday
    assert_equal Date.civil(2015, 12, 30), matching_holiday[:date]
    assert_includes matching_holiday[:regions], :ph


  end
end
