# encoding: utf-8
require File.expand_path(File.dirname(__FILE__)) + '/../test_helper'

# This file is generated by the Ruby Holiday gem.
#
# Definitions loaded: definitions/tr.yaml
class TrDefinitionTests < Test::Unit::TestCase  # :nodoc:

  def test_tr
    holidays = Holidays.on(Date.civil(2017, 1, 1), [:tr])
    matching_holiday = holidays.find { |hol| hol[:name] == "Yılbaşı" }
    assert_not_nil matching_holiday
    assert_equal Date.civil(2017, 1, 1), matching_holiday[:date]
    assert_includes matching_holiday[:regions], :tr


    holidays = Holidays.on(Date.civil(2017, 4, 23), [:tr])
    matching_holiday = holidays.find { |hol| hol[:name] == "Ulusal Egemenlik ve Çocuk Bayramı" }
    assert_not_nil matching_holiday
    assert_equal Date.civil(2017, 4, 23), matching_holiday[:date]
    assert_includes matching_holiday[:regions], :tr


    holidays = Holidays.on(Date.civil(2017, 5, 1), [:tr])
    matching_holiday = holidays.find { |hol| hol[:name] == "Emek ve Dayanışma Günü" }
    assert_not_nil matching_holiday
    assert_equal Date.civil(2017, 5, 1), matching_holiday[:date]
    assert_includes matching_holiday[:regions], :tr


    holidays = Holidays.on(Date.civil(2017, 5, 19), [:tr])
    matching_holiday = holidays.find { |hol| hol[:name] == "Atatürk'ü Anma Gençlik ve Spor Bayramı" }
    assert_not_nil matching_holiday
    assert_equal Date.civil(2017, 5, 19), matching_holiday[:date]
    assert_includes matching_holiday[:regions], :tr


    holidays = Holidays.on(Date.civil(2017, 8, 30), [:tr])
    matching_holiday = holidays.find { |hol| hol[:name] == "Zafer Bayramı" }
    assert_not_nil matching_holiday
    assert_equal Date.civil(2017, 8, 30), matching_holiday[:date]
    assert_includes matching_holiday[:regions], :tr


    holidays = Holidays.on(Date.civil(2017, 10, 29), [:tr])
    matching_holiday = holidays.find { |hol| hol[:name] == "Cumhuriyet Bayramı" }
    assert_not_nil matching_holiday
    assert_equal Date.civil(2017, 10, 29), matching_holiday[:date]
    assert_includes matching_holiday[:regions], :tr


    holidays = Holidays.on(Date.civil(2017, 6, 25), [:tr])
    matching_holiday = holidays.find { |hol| hol[:name] == "Ramazan Bayramı" }
    assert_not_nil matching_holiday
    assert_equal Date.civil(2017, 6, 25), matching_holiday[:date]
    assert_includes matching_holiday[:regions], :tr

    holidays = Holidays.on(Date.civil(2018, 6, 15), [:tr])
    matching_holiday = holidays.find { |hol| hol[:name] == "Ramazan Bayramı" }
    assert_not_nil matching_holiday
    assert_equal Date.civil(2018, 6, 15), matching_holiday[:date]
    assert_includes matching_holiday[:regions], :tr

    holidays = Holidays.on(Date.civil(2019, 6, 4), [:tr])
    matching_holiday = holidays.find { |hol| hol[:name] == "Ramazan Bayramı" }
    assert_not_nil matching_holiday
    assert_equal Date.civil(2019, 6, 4), matching_holiday[:date]
    assert_includes matching_holiday[:regions], :tr


    holidays = Holidays.on(Date.civil(2017, 6, 26), [:tr])
    matching_holiday = holidays.find { |hol| hol[:name] == "Ramazan Bayramı (ikinci tatil)" }
    assert_not_nil matching_holiday
    assert_equal Date.civil(2017, 6, 26), matching_holiday[:date]
    assert_includes matching_holiday[:regions], :tr

    holidays = Holidays.on(Date.civil(2018, 6, 16), [:tr])
    matching_holiday = holidays.find { |hol| hol[:name] == "Ramazan Bayramı (ikinci tatil)" }
    assert_not_nil matching_holiday
    assert_equal Date.civil(2018, 6, 16), matching_holiday[:date]
    assert_includes matching_holiday[:regions], :tr

    holidays = Holidays.on(Date.civil(2019, 6, 5), [:tr])
    matching_holiday = holidays.find { |hol| hol[:name] == "Ramazan Bayramı (ikinci tatil)" }
    assert_not_nil matching_holiday
    assert_equal Date.civil(2019, 6, 5), matching_holiday[:date]
    assert_includes matching_holiday[:regions], :tr


    holidays = Holidays.on(Date.civil(2017, 6, 27), [:tr])
    matching_holiday = holidays.find { |hol| hol[:name] == "Ramazan Bayramı (üçüncü tatil)" }
    assert_not_nil matching_holiday
    assert_equal Date.civil(2017, 6, 27), matching_holiday[:date]
    assert_includes matching_holiday[:regions], :tr

    holidays = Holidays.on(Date.civil(2018, 6, 17), [:tr])
    matching_holiday = holidays.find { |hol| hol[:name] == "Ramazan Bayramı (üçüncü tatil)" }
    assert_not_nil matching_holiday
    assert_equal Date.civil(2018, 6, 17), matching_holiday[:date]
    assert_includes matching_holiday[:regions], :tr

    holidays = Holidays.on(Date.civil(2019, 6, 6), [:tr])
    matching_holiday = holidays.find { |hol| hol[:name] == "Ramazan Bayramı (üçüncü tatil)" }
    assert_not_nil matching_holiday
    assert_equal Date.civil(2019, 6, 6), matching_holiday[:date]
    assert_includes matching_holiday[:regions], :tr


    holidays = Holidays.on(Date.civil(2017, 7, 15), [:tr])
    matching_holiday = holidays.find { |hol| hol[:name] == "Demokrasi ve Milli Birlik Günü" }
    assert_not_nil matching_holiday
    assert_equal Date.civil(2017, 7, 15), matching_holiday[:date]
    assert_includes matching_holiday[:regions], :tr


    holidays = Holidays.on(Date.civil(2017, 9, 1), [:tr])
    matching_holiday = holidays.find { |hol| hol[:name] == "Kurban Bayramı" }
    assert_not_nil matching_holiday
    assert_equal Date.civil(2017, 9, 1), matching_holiday[:date]
    assert_includes matching_holiday[:regions], :tr

    holidays = Holidays.on(Date.civil(2018, 8, 21), [:tr])
    matching_holiday = holidays.find { |hol| hol[:name] == "Kurban Bayramı" }
    assert_not_nil matching_holiday
    assert_equal Date.civil(2018, 8, 21), matching_holiday[:date]
    assert_includes matching_holiday[:regions], :tr

    holidays = Holidays.on(Date.civil(2019, 8, 11), [:tr])
    matching_holiday = holidays.find { |hol| hol[:name] == "Kurban Bayramı" }
    assert_not_nil matching_holiday
    assert_equal Date.civil(2019, 8, 11), matching_holiday[:date]
    assert_includes matching_holiday[:regions], :tr


    holidays = Holidays.on(Date.civil(2017, 9, 2), [:tr])
    matching_holiday = holidays.find { |hol| hol[:name] == "Kurban Bayramı (ikinci tatil)" }
    assert_not_nil matching_holiday
    assert_equal Date.civil(2017, 9, 2), matching_holiday[:date]
    assert_includes matching_holiday[:regions], :tr

    holidays = Holidays.on(Date.civil(2018, 8, 22), [:tr])
    matching_holiday = holidays.find { |hol| hol[:name] == "Kurban Bayramı (ikinci tatil)" }
    assert_not_nil matching_holiday
    assert_equal Date.civil(2018, 8, 22), matching_holiday[:date]
    assert_includes matching_holiday[:regions], :tr

    holidays = Holidays.on(Date.civil(2019, 8, 12), [:tr])
    matching_holiday = holidays.find { |hol| hol[:name] == "Kurban Bayramı (ikinci tatil)" }
    assert_not_nil matching_holiday
    assert_equal Date.civil(2019, 8, 12), matching_holiday[:date]
    assert_includes matching_holiday[:regions], :tr


    holidays = Holidays.on(Date.civil(2017, 9, 3), [:tr])
    matching_holiday = holidays.find { |hol| hol[:name] == "Kurban Bayramı (üçüncü tatil)" }
    assert_not_nil matching_holiday
    assert_equal Date.civil(2017, 9, 3), matching_holiday[:date]
    assert_includes matching_holiday[:regions], :tr

    holidays = Holidays.on(Date.civil(2018, 8, 23), [:tr])
    matching_holiday = holidays.find { |hol| hol[:name] == "Kurban Bayramı (üçüncü tatil)" }
    assert_not_nil matching_holiday
    assert_equal Date.civil(2018, 8, 23), matching_holiday[:date]
    assert_includes matching_holiday[:regions], :tr

    holidays = Holidays.on(Date.civil(2019, 8, 13), [:tr])
    matching_holiday = holidays.find { |hol| hol[:name] == "Kurban Bayramı (üçüncü tatil)" }
    assert_not_nil matching_holiday
    assert_equal Date.civil(2019, 8, 13), matching_holiday[:date]
    assert_includes matching_holiday[:regions], :tr


    holidays = Holidays.on(Date.civil(2017, 9, 4), [:tr])
    matching_holiday = holidays.find { |hol| hol[:name] == "Kurban Bayramı (dördüncü tatil)" }
    assert_not_nil matching_holiday
    assert_equal Date.civil(2017, 9, 4), matching_holiday[:date]
    assert_includes matching_holiday[:regions], :tr

    holidays = Holidays.on(Date.civil(2018, 8, 24), [:tr])
    matching_holiday = holidays.find { |hol| hol[:name] == "Kurban Bayramı (dördüncü tatil)" }
    assert_not_nil matching_holiday
    assert_equal Date.civil(2018, 8, 24), matching_holiday[:date]
    assert_includes matching_holiday[:regions], :tr

    holidays = Holidays.on(Date.civil(2019, 8, 14), [:tr])
    matching_holiday = holidays.find { |hol| hol[:name] == "Kurban Bayramı (dördüncü tatil)" }
    assert_not_nil matching_holiday
    assert_equal Date.civil(2019, 8, 14), matching_holiday[:date]
    assert_includes matching_holiday[:regions], :tr


  end
end
