# encoding: utf-8
require File.expand_path(File.dirname(__FILE__)) + '/../test_helper'

# This file is generated by the Ruby Holiday gem.
#
# Definitions loaded: definitions/na.yaml
class NaDefinitionTests < Test::Unit::TestCase  # :nodoc:

  def test_na
    holidays = Holidays.on(Date.civil(2018, 1, 1), [:na])
    matching_holiday = holidays.find { |hol| hol[:name] == "New Years Days" }
    assert_not_nil matching_holiday
    assert_equal Date.civil(2018, 1, 1), matching_holiday[:date]
    assert_includes matching_holiday[:regions], :na


    holidays = Holidays.on(Date.civil(2018, 3, 30), [:na])
    matching_holiday = holidays.find { |hol| hol[:name] == "Good Friday" }
    assert_not_nil matching_holiday
    assert_equal Date.civil(2018, 3, 30), matching_holiday[:date]
    assert_includes matching_holiday[:regions], :na


    holidays = Holidays.on(Date.civil(2018, 4, 2), [:na])
    matching_holiday = holidays.find { |hol| hol[:name] == "Easter Monday" }
    assert_not_nil matching_holiday
    assert_equal Date.civil(2018, 4, 2), matching_holiday[:date]
    assert_includes matching_holiday[:regions], :na


    holidays = Holidays.on(Date.civil(2018, 5, 10), [:na])
    matching_holiday = holidays.find { |hol| hol[:name] == "Ascension Day" }
    assert_not_nil matching_holiday
    assert_equal Date.civil(2018, 5, 10), matching_holiday[:date]
    assert_includes matching_holiday[:regions], :na


    holidays = Holidays.on(Date.civil(2018, 8, 27), [:na], [:observed])
    matching_holiday = holidays.find { |hol| hol[:name] == "Heroes' Day" }
    assert_not_nil matching_holiday
    assert_equal Date.civil(2018, 8, 27), matching_holiday[:date]
    assert_includes matching_holiday[:regions], :na


    holidays = Holidays.on(Date.civil(2019, 4, 22), [:na])
    matching_holiday = holidays.find { |hol| hol[:name] == "Easter Monday" }
    assert_not_nil matching_holiday
    assert_equal Date.civil(2019, 4, 22), matching_holiday[:date]
    assert_includes matching_holiday[:regions], :na


    holidays = Holidays.on(Date.civil(2019, 5, 30), [:na])
    matching_holiday = holidays.find { |hol| hol[:name] == "Ascension Day" }
    assert_not_nil matching_holiday
    assert_equal Date.civil(2019, 5, 30), matching_holiday[:date]
    assert_includes matching_holiday[:regions], :na


    holidays = Holidays.on(Date.civil(2019, 8, 26), [:na])
    matching_holiday = holidays.find { |hol| hol[:name] == "Heroes' Day" }
    assert_not_nil matching_holiday
    assert_equal Date.civil(2019, 8, 26), matching_holiday[:date]
    assert_includes matching_holiday[:regions], :na


  end
end
