# encoding: utf-8
require File.expand_path(File.dirname(__FILE__)) + '/../test_helper'

# This file is generated by the Ruby Holiday gem.
#
# Definitions loaded: definitions/jp.yaml
class JpDefinitionTests < Test::Unit::TestCase  # :nodoc:

  def test_jp
    holidays = Holidays.on(Date.civil(2008, 1, 1), [:jp], [:informal])
    matching_holiday = holidays.find { |hol| hol[:name] == "元日" }
    assert_not_nil matching_holiday
    assert_equal Date.civil(2008, 1, 1), matching_holiday[:date]
    assert_includes matching_holiday[:regions], :jp


    holidays = Holidays.on(Date.civil(2010, 1, 11), [:jp], [:informal])
    matching_holiday = holidays.find { |hol| hol[:name] == "成人の日" }
    assert_not_nil matching_holiday
    assert_equal Date.civil(2010, 1, 11), matching_holiday[:date]
    assert_includes matching_holiday[:regions], :jp


    holidays = Holidays.on(Date.civil(2008, 2, 11), [:jp], [:informal])
    matching_holiday = holidays.find { |hol| hol[:name] == "建国記念の日" }
    assert_not_nil matching_holiday
    assert_equal Date.civil(2008, 2, 11), matching_holiday[:date]
    assert_includes matching_holiday[:regions], :jp


    holidays = Holidays.on(Date.civil(2008, 4, 29), [:jp], [:informal])
    matching_holiday = holidays.find { |hol| hol[:name] == "昭和の日" }
    assert_not_nil matching_holiday
    assert_equal Date.civil(2008, 4, 29), matching_holiday[:date]
    assert_includes matching_holiday[:regions], :jp


    holidays = Holidays.on(Date.civil(2008, 5, 3), [:jp], [:informal])
    matching_holiday = holidays.find { |hol| hol[:name] == "憲法記念日" }
    assert_not_nil matching_holiday
    assert_equal Date.civil(2008, 5, 3), matching_holiday[:date]
    assert_includes matching_holiday[:regions], :jp


    holidays = Holidays.on(Date.civil(2008, 5, 5), [:jp], [:informal])
    matching_holiday = holidays.find { |hol| hol[:name] == "こどもの日" }
    assert_not_nil matching_holiday
    assert_equal Date.civil(2008, 5, 5), matching_holiday[:date]
    assert_includes matching_holiday[:regions], :jp


    holidays = Holidays.on(Date.civil(2010, 7, 19), [:jp], [:informal])
    matching_holiday = holidays.find { |hol| hol[:name] == "海の日" }
    assert_not_nil matching_holiday
    assert_equal Date.civil(2010, 7, 19), matching_holiday[:date]
    assert_includes matching_holiday[:regions], :jp


    holidays = Holidays.on(Date.civil(2010, 9, 20), [:jp], [:informal])
    matching_holiday = holidays.find { |hol| hol[:name] == "敬老の日" }
    assert_not_nil matching_holiday
    assert_equal Date.civil(2010, 9, 20), matching_holiday[:date]
    assert_includes matching_holiday[:regions], :jp


    holidays = Holidays.on(Date.civil(2010, 10, 11), [:jp], [:informal])
    matching_holiday = holidays.find { |hol| hol[:name] == "体育の日" }
    assert_not_nil matching_holiday
    assert_equal Date.civil(2010, 10, 11), matching_holiday[:date]
    assert_includes matching_holiday[:regions], :jp


    holidays = Holidays.on(Date.civil(2008, 11, 3), [:jp], [:informal])
    matching_holiday = holidays.find { |hol| hol[:name] == "文化の日" }
    assert_not_nil matching_holiday
    assert_equal Date.civil(2008, 11, 3), matching_holiday[:date]
    assert_includes matching_holiday[:regions], :jp


    holidays = Holidays.on(Date.civil(2008, 11, 23), [:jp], [:informal])
    matching_holiday = holidays.find { |hol| hol[:name] == "勤労感謝の日" }
    assert_not_nil matching_holiday
    assert_equal Date.civil(2008, 11, 23), matching_holiday[:date]
    assert_includes matching_holiday[:regions], :jp


    holidays = Holidays.on(Date.civil(2008, 12, 23), [:jp], [:informal])
    matching_holiday = holidays.find { |hol| hol[:name] == "天皇誕生日" }
    assert_not_nil matching_holiday
    assert_equal Date.civil(2008, 12, 23), matching_holiday[:date]
    assert_includes matching_holiday[:regions], :jp


    holidays = Holidays.on(Date.civil(2010, 3, 22), [:jp], [:informal])
    matching_holiday = holidays.find { |hol| hol[:name] == "振替休日" }
    assert_not_nil matching_holiday
    assert_equal Date.civil(2010, 3, 22), matching_holiday[:date]
    assert_includes matching_holiday[:regions], :jp


    holidays = Holidays.on(Date.civil(2008, 11, 24), [:jp], [:informal])
    matching_holiday = holidays.find { |hol| hol[:name] == "振替休日" }
    assert_not_nil matching_holiday
    assert_equal Date.civil(2008, 11, 24), matching_holiday[:date]
    assert_includes matching_holiday[:regions], :jp


    holidays = Holidays.on(Date.civil(2012, 1, 2), [:jp], [:informal])
    matching_holiday = holidays.find { |hol| hol[:name] == "振替休日" }
    assert_not_nil matching_holiday
    assert_equal Date.civil(2012, 1, 2), matching_holiday[:date]
    assert_includes matching_holiday[:regions], :jp


    holidays = Holidays.on(Date.civil(2013, 5, 6), [:jp], [:informal])
    matching_holiday = holidays.find { |hol| hol[:name] == "振替休日" }
    assert_not_nil matching_holiday
    assert_equal Date.civil(2013, 5, 6), matching_holiday[:date]
    assert_includes matching_holiday[:regions], :jp


    holidays = Holidays.on(Date.civil(2014, 5, 6), [:jp], [:informal])
    matching_holiday = holidays.find { |hol| hol[:name] == "振替休日" }
    assert_not_nil matching_holiday
    assert_equal Date.civil(2014, 5, 6), matching_holiday[:date]
    assert_includes matching_holiday[:regions], :jp


    holidays = Holidays.on(Date.civil(2015, 5, 6), [:jp], [:informal])
    matching_holiday = holidays.find { |hol| hol[:name] == "振替休日" }
    assert_not_nil matching_holiday
    assert_equal Date.civil(2015, 5, 6), matching_holiday[:date]
    assert_includes matching_holiday[:regions], :jp


    holidays = Holidays.on(Date.civil(2019, 8, 12), [:jp], [:informal])
    matching_holiday = holidays.find { |hol| hol[:name] == "振替休日" }
    assert_not_nil matching_holiday
    assert_equal Date.civil(2019, 8, 12), matching_holiday[:date]
    assert_includes matching_holiday[:regions], :jp


    holidays = Holidays.on(Date.civil(2004, 3, 20), [:jp])
    matching_holiday = holidays.find { |hol| hol[:name] == "春分の日" }
    assert_not_nil matching_holiday
    assert_equal Date.civil(2004, 3, 20), matching_holiday[:date]
    assert_includes matching_holiday[:regions], :jp


    holidays = Holidays.on(Date.civil(2005, 3, 20), [:jp])
    matching_holiday = holidays.find { |hol| hol[:name] == "春分の日" }
    assert_not_nil matching_holiday
    assert_equal Date.civil(2005, 3, 20), matching_holiday[:date]
    assert_includes matching_holiday[:regions], :jp


    holidays = Holidays.on(Date.civil(2006, 3, 21), [:jp])
    matching_holiday = holidays.find { |hol| hol[:name] == "春分の日" }
    assert_not_nil matching_holiday
    assert_equal Date.civil(2006, 3, 21), matching_holiday[:date]
    assert_includes matching_holiday[:regions], :jp


    holidays = Holidays.on(Date.civil(2007, 3, 21), [:jp])
    matching_holiday = holidays.find { |hol| hol[:name] == "春分の日" }
    assert_not_nil matching_holiday
    assert_equal Date.civil(2007, 3, 21), matching_holiday[:date]
    assert_includes matching_holiday[:regions], :jp


    holidays = Holidays.on(Date.civil(2008, 3, 20), [:jp])
    matching_holiday = holidays.find { |hol| hol[:name] == "春分の日" }
    assert_not_nil matching_holiday
    assert_equal Date.civil(2008, 3, 20), matching_holiday[:date]
    assert_includes matching_holiday[:regions], :jp


    holidays = Holidays.on(Date.civil(2009, 3, 20), [:jp])
    matching_holiday = holidays.find { |hol| hol[:name] == "春分の日" }
    assert_not_nil matching_holiday
    assert_equal Date.civil(2009, 3, 20), matching_holiday[:date]
    assert_includes matching_holiday[:regions], :jp


    holidays = Holidays.on(Date.civil(2010, 3, 21), [:jp])
    matching_holiday = holidays.find { |hol| hol[:name] == "春分の日" }
    assert_not_nil matching_holiday
    assert_equal Date.civil(2010, 3, 21), matching_holiday[:date]
    assert_includes matching_holiday[:regions], :jp


    holidays = Holidays.on(Date.civil(2004, 9, 23), [:jp])
    matching_holiday = holidays.find { |hol| hol[:name] == "秋分の日" }
    assert_not_nil matching_holiday
    assert_equal Date.civil(2004, 9, 23), matching_holiday[:date]
    assert_includes matching_holiday[:regions], :jp


    holidays = Holidays.on(Date.civil(2005, 9, 23), [:jp])
    matching_holiday = holidays.find { |hol| hol[:name] == "秋分の日" }
    assert_not_nil matching_holiday
    assert_equal Date.civil(2005, 9, 23), matching_holiday[:date]
    assert_includes matching_holiday[:regions], :jp


    holidays = Holidays.on(Date.civil(2006, 9, 23), [:jp])
    matching_holiday = holidays.find { |hol| hol[:name] == "秋分の日" }
    assert_not_nil matching_holiday
    assert_equal Date.civil(2006, 9, 23), matching_holiday[:date]
    assert_includes matching_holiday[:regions], :jp


    holidays = Holidays.on(Date.civil(2007, 9, 23), [:jp])
    matching_holiday = holidays.find { |hol| hol[:name] == "秋分の日" }
    assert_not_nil matching_holiday
    assert_equal Date.civil(2007, 9, 23), matching_holiday[:date]
    assert_includes matching_holiday[:regions], :jp


    holidays = Holidays.on(Date.civil(2008, 9, 23), [:jp])
    matching_holiday = holidays.find { |hol| hol[:name] == "秋分の日" }
    assert_not_nil matching_holiday
    assert_equal Date.civil(2008, 9, 23), matching_holiday[:date]
    assert_includes matching_holiday[:regions], :jp


    holidays = Holidays.on(Date.civil(2009, 9, 23), [:jp])
    matching_holiday = holidays.find { |hol| hol[:name] == "秋分の日" }
    assert_not_nil matching_holiday
    assert_equal Date.civil(2009, 9, 23), matching_holiday[:date]
    assert_includes matching_holiday[:regions], :jp


    holidays = Holidays.on(Date.civil(2010, 9, 23), [:jp])
    matching_holiday = holidays.find { |hol| hol[:name] == "秋分の日" }
    assert_not_nil matching_holiday
    assert_equal Date.civil(2010, 9, 23), matching_holiday[:date]
    assert_includes matching_holiday[:regions], :jp


    holidays = Holidays.on(Date.civil(2011, 9, 23), [:jp])
    matching_holiday = holidays.find { |hol| hol[:name] == "秋分の日" }
    assert_not_nil matching_holiday
    assert_equal Date.civil(2011, 9, 23), matching_holiday[:date]
    assert_includes matching_holiday[:regions], :jp


    holidays = Holidays.on(Date.civil(2012, 9, 22), [:jp])
    matching_holiday = holidays.find { |hol| hol[:name] == "秋分の日" }
    assert_not_nil matching_holiday
    assert_equal Date.civil(2012, 9, 22), matching_holiday[:date]
    assert_includes matching_holiday[:regions], :jp


    holidays = Holidays.on(Date.civil(2013, 9, 23), [:jp])
    matching_holiday = holidays.find { |hol| hol[:name] == "秋分の日" }
    assert_not_nil matching_holiday
    assert_equal Date.civil(2013, 9, 23), matching_holiday[:date]
    assert_includes matching_holiday[:regions], :jp


    holidays = Holidays.on(Date.civil(2032, 9, 21), [:jp])
    matching_holiday = holidays.find { |hol| hol[:name] == "国民の休日" }
    assert_not_nil matching_holiday
    assert_equal Date.civil(2032, 9, 21), matching_holiday[:date]
    assert_includes matching_holiday[:regions], :jp


    holidays = Holidays.on(Date.civil(2049, 9, 21), [:jp])
    matching_holiday = holidays.find { |hol| hol[:name] == "国民の休日" }
    assert_not_nil matching_holiday
    assert_equal Date.civil(2049, 9, 21), matching_holiday[:date]
    assert_includes matching_holiday[:regions], :jp


    holidays = Holidays.on(Date.civil(2009, 9, 22), [:jp])
    matching_holiday = holidays.find { |hol| hol[:name] == "国民の休日" }
    assert_not_nil matching_holiday
    assert_equal Date.civil(2009, 9, 22), matching_holiday[:date]
    assert_includes matching_holiday[:regions], :jp


    holidays = Holidays.on(Date.civil(2015, 9, 22), [:jp])
    matching_holiday = holidays.find { |hol| hol[:name] == "国民の休日" }
    assert_not_nil matching_holiday
    assert_equal Date.civil(2015, 9, 22), matching_holiday[:date]
    assert_includes matching_holiday[:regions], :jp


    holidays = Holidays.on(Date.civil(2026, 9, 22), [:jp])
    matching_holiday = holidays.find { |hol| hol[:name] == "国民の休日" }
    assert_not_nil matching_holiday
    assert_equal Date.civil(2026, 9, 22), matching_holiday[:date]
    assert_includes matching_holiday[:regions], :jp


    holidays = Holidays.on(Date.civil(1996, 7, 20), [:jp])
    matching_holiday = holidays.find { |hol| hol[:name] == "海の日" }
    assert_not_nil matching_holiday
    assert_equal Date.civil(1996, 7, 20), matching_holiday[:date]
    assert_includes matching_holiday[:regions], :jp


    holidays = Holidays.on(Date.civil(2002, 7, 20), [:jp])
    matching_holiday = holidays.find { |hol| hol[:name] == "海の日" }
    assert_not_nil matching_holiday
    assert_equal Date.civil(2002, 7, 20), matching_holiday[:date]
    assert_includes matching_holiday[:regions], :jp


    holidays = Holidays.on(Date.civil(2003, 7, 21), [:jp])
    matching_holiday = holidays.find { |hol| hol[:name] == "海の日" }
    assert_not_nil matching_holiday
    assert_equal Date.civil(2003, 7, 21), matching_holiday[:date]
    assert_includes matching_holiday[:regions], :jp


    holidays = Holidays.on(Date.civil(2004, 7, 19), [:jp])
    matching_holiday = holidays.find { |hol| hol[:name] == "海の日" }
    assert_not_nil matching_holiday
    assert_equal Date.civil(2004, 7, 19), matching_holiday[:date]
    assert_includes matching_holiday[:regions], :jp


    holidays = Holidays.on(Date.civil(2005, 7, 18), [:jp])
    matching_holiday = holidays.find { |hol| hol[:name] == "海の日" }
    assert_not_nil matching_holiday
    assert_equal Date.civil(2005, 7, 18), matching_holiday[:date]
    assert_includes matching_holiday[:regions], :jp


    holidays = Holidays.on(Date.civil(2006, 7, 17), [:jp])
    matching_holiday = holidays.find { |hol| hol[:name] == "海の日" }
    assert_not_nil matching_holiday
    assert_equal Date.civil(2006, 7, 17), matching_holiday[:date]
    assert_includes matching_holiday[:regions], :jp


    holidays = Holidays.on(Date.civil(2007, 7, 16), [:jp])
    matching_holiday = holidays.find { |hol| hol[:name] == "海の日" }
    assert_not_nil matching_holiday
    assert_equal Date.civil(2007, 7, 16), matching_holiday[:date]
    assert_includes matching_holiday[:regions], :jp


    holidays = Holidays.on(Date.civil(2009, 7, 20), [:jp])
    matching_holiday = holidays.find { |hol| hol[:name] == "海の日" }
    assert_not_nil matching_holiday
    assert_equal Date.civil(2009, 7, 20), matching_holiday[:date]
    assert_includes matching_holiday[:regions], :jp


    holidays = Holidays.on(Date.civil(2013, 7, 15), [:jp])
    matching_holiday = holidays.find { |hol| hol[:name] == "海の日" }
    assert_not_nil matching_holiday
    assert_equal Date.civil(2013, 7, 15), matching_holiday[:date]
    assert_includes matching_holiday[:regions], :jp


    holidays = Holidays.on(Date.civil(2014, 7, 21), [:jp])
    matching_holiday = holidays.find { |hol| hol[:name] == "海の日" }
    assert_not_nil matching_holiday
    assert_equal Date.civil(2014, 7, 21), matching_holiday[:date]
    assert_includes matching_holiday[:regions], :jp


    holidays = Holidays.on(Date.civil(2016, 8, 11), [:jp])
    matching_holiday = holidays.find { |hol| hol[:name] == "山の日" }
    assert_not_nil matching_holiday
    assert_equal Date.civil(2016, 8, 11), matching_holiday[:date]
    assert_includes matching_holiday[:regions], :jp


    holidays = Holidays.on(Date.civil(2017, 8, 11), [:jp])
    matching_holiday = holidays.find { |hol| hol[:name] == "山の日" }
    assert_not_nil matching_holiday
    assert_equal Date.civil(2017, 8, 11), matching_holiday[:date]
    assert_includes matching_holiday[:regions], :jp


    holidays = Holidays.on(Date.civil(2018, 8, 11), [:jp])
    matching_holiday = holidays.find { |hol| hol[:name] == "山の日" }
    assert_not_nil matching_holiday
    assert_equal Date.civil(2018, 8, 11), matching_holiday[:date]
    assert_includes matching_holiday[:regions], :jp


    holidays = Holidays.on(Date.civil(2019, 8, 11), [:jp])
    matching_holiday = holidays.find { |hol| hol[:name] == "山の日" }
    assert_not_nil matching_holiday
    assert_equal Date.civil(2019, 8, 11), matching_holiday[:date]
    assert_includes matching_holiday[:regions], :jp


    holidays = Holidays.on(Date.civil(2020, 8, 11), [:jp])
    matching_holiday = holidays.find { |hol| hol[:name] == "山の日" }
    assert_not_nil matching_holiday
    assert_equal Date.civil(2020, 8, 11), matching_holiday[:date]
    assert_includes matching_holiday[:regions], :jp


    holidays = Holidays.on(Date.civil(2021, 8, 11), [:jp])
    matching_holiday = holidays.find { |hol| hol[:name] == "山の日" }
    assert_not_nil matching_holiday
    assert_equal Date.civil(2021, 8, 11), matching_holiday[:date]
    assert_includes matching_holiday[:regions], :jp


    holidays = Holidays.on(Date.civil(2022, 8, 11), [:jp])
    matching_holiday = holidays.find { |hol| hol[:name] == "山の日" }
    assert_not_nil matching_holiday
    assert_equal Date.civil(2022, 8, 11), matching_holiday[:date]
    assert_includes matching_holiday[:regions], :jp


    assert_nil (Holidays.on(Date.civil(2015, 8, 11), [:jp])[0] || {})[:name]

    assert_nil (Holidays.on(Date.civil(1998, 9, 22), [:jp])[0] || {})[:name]

    holidays = Holidays.on(Date.civil(2018, 12, 23), [:jp])
    matching_holiday = holidays.find { |hol| hol[:name] == "天皇誕生日" }
    assert_not_nil matching_holiday
    assert_equal Date.civil(2018, 12, 23), matching_holiday[:date]
    assert_includes matching_holiday[:regions], :jp


    assert_nil (Holidays.on(Date.civil(2019, 2, 23), [:jp])[0] || {})[:name]

    assert_nil (Holidays.on(Date.civil(2019, 12, 23), [:jp])[0] || {})[:name]

    holidays = Holidays.on(Date.civil(2020, 2, 23), [:jp])
    matching_holiday = holidays.find { |hol| hol[:name] == "天皇誕生日" }
    assert_not_nil matching_holiday
    assert_equal Date.civil(2020, 2, 23), matching_holiday[:date]
    assert_includes matching_holiday[:regions], :jp


  end
end
