# encoding: utf-8
module Holidays
  # This file is generated by the Ruby Holidays gem.
  #
  # Definitions loaded: definitions/do.yaml
  #
  # All the definitions are available at https://github.com/holidays/holidays
  module DO # :nodoc:
    def self.defined_regions
      [:do]
    end

    def self.holidays_by_month
      {
              0 => [{:function => "easter(year)", :function_arguments => [:year], :function_modifier => -2, :name => "Viernes Santo", :regions => [:do]},
            {:function => "easter(year)", :function_arguments => [:year], :name => "Dia de Pascua", :regions => [:do]},
            {:function => "easter(year)", :function_arguments => [:year], :function_modifier => 60, :name => "Corpus Christi", :regions => [:do]}],
      1 => [{:mday => 1, :name => "Año Nuevo", :regions => [:do]},
            {:function => "epiphany(year)", :function_arguments => [:year], :name => "Epifanía", :regions => [:do]},
            {:mday => 21, :name => "Día de la Altagracia", :regions => [:do]},
            {:mday => 26, :name => "Juan Pablo Duarte", :regions => [:do]}],
      2 => [{:mday => 27, :name => "Día de la Independencia", :regions => [:do]}],
      5 => [{:function => "labor_day(year)", :function_arguments => [:year], :name => "Dia del Trabajo", :regions => [:do]}],
      8 => [{:mday => 16, :name => "Día de la Restauración", :regions => [:do]}],
      9 => [{:mday => 24, :name => "Día de Nuestra Señora de Mercedes", :regions => [:do]}],
      11 => [{:function => "constitution_day(year)", :function_arguments => [:year], :name => "Día de la Constitución", :regions => [:do]}],
      12 => [{:mday => 25, :name => "Navidad", :regions => [:do]}]
      }
    end

    def self.custom_methods
      {
        "epiphany(year)" => Proc.new { |year|
date = Date.civil(year, 1, 6)
if [2,3,4].include?(date.wday)
  date -= (date.wday - 1)
elsif date.wday == 5
  date += 3
end

date
},

"labor_day(year)" => Proc.new { |year|
date = Date.civil(year, 5, 1)
if [2,3,4].include?(date.wday)
  date -= (date.wday - 1)
elsif date.wday == 5
  date += 3
end

date
},

"constitution_day(year)" => Proc.new { |year|
date = Date.civil(year, 11, 6)
if [2,3,4].include?(date.wday)
  date -= (date.wday - 1)
elsif date.wday == 5
  date += 3
end

date
},


      }
    end
  end
end
